### ISSUE TITLE
[BUG] MemoryError on lost connection.

### ISSUE THREAD

**Issue by whataboutpereira** [rdiff-backup/rdiff-backup#355] opened 2020-05-11 11:33 UTC
## Bug summary

A scheduled rdiff-backup run yielded a MemoryError. This happened only once and looking at system logs from the same moment I didn't see anything out of place.

## Version, Python, Operating System

```
2020-05-11 14:27:03.978579 +0300  <CLIENT-676>  Using rdiff-backup version 2.0.0
2020-05-11 14:27:03.978767 +0300  <CLIENT-676>          with cpython /usr/bin/python3.6 version 3.6.8
2020-05-11 14:27:03.983848 +0300  <CLIENT-676>          on Linux-5.3.18-3-pve-x86_64-with-centos-8.1.1911-Core, fs encoding utf-8
```

## rdiff-backup call

```
rdiff-backup --force --ssh-no-compression --no-hard-links --include-globbing-filelist @config/host.txt --print-statistics root@host::/ host/
```

## What happened and what did you expect?

There seems to have been a connection error between the 2 systems:

`Fatal Error: Lost connection to the remote system`

However this resulted in a MemoryError for rdiff-backup as seen from the below log.

## More information

```
Sun May 10 18:15:07 EEST 2020:

Exception '' raised of class '<class 'MemoryError'>':
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 409, in Main
    rps = list(map(SetConnections.cmdpair2rp, cmdpairs))
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/SetConnections.py", line 85, in cmdpair2rp
    conn = init_connection(cmd)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/SetConnections.py", line 191, in init_connection
    check_connection_version(conn, remote_cmd)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/SetConnections.py", line 201, in check_connection_version
    remote_version = conn.Globals.get('version')
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 526, in __call__
    return self.connection.reval(*(self.name, ) + args)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 436, in reval
    result = self.get_response(req_num)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 379, in get_response
    req_num, object = self._get()
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 293, in _get
    data = self._read(length)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 266, in _read
    return self.inpipe.read(length)

Traceback (most recent call last):
  File "/usr/local/bin/rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 409, in Main
    rps = list(map(SetConnections.cmdpair2rp, cmdpairs))
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/SetConnections.py", line 85, in cmdpair2rp
    conn = init_connection(cmd)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/SetConnections.py", line 191, in init_connection
    check_connection_version(conn, remote_cmd)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/SetConnections.py", line 201, in check_connection_version
    remote_version = conn.Globals.get('version')
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 526, in __call__
    return self.connection.reval(*(self.name, ) + args)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 436, in reval
    result = self.get_response(req_num)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 379, in get_response
    req_num, object = self._get()
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 293, in _get
    data = self._read(length)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 266, in _read
    return self.inpipe.read(length)
MemoryError
Fatal Error: Lost connection to the remote system
```

**Comment by ericzolf** [comment] 2020-05-11 20:26
Did you get the issue only once or is it something happening regularly/always? Can you reproduce it with verbosity 9?

**Comment by ericzolf** [comment] 2020-05-11 20:27
Just for reference: issue might be related to issue #21

**Comment by ericzolf** [comment] 2020-05-11 20:28
Sorry, I oversaw your "only once".

**Comment by ericzolf** [comment] 2020-05-13 20:28
I don't see as a critical bug as it seems only to happen due to an underlying connection issue, but I admit that it should be handled better. We'll look into it in due time.

**Comment by ericzolf** [comment] 2020-06-18 07:31
From my analysis, the error can only happen if the connection exactly drops at the wrong time for rdiff-backup to read a wrong length value and then choke on it. This is rather uncommon, it would require to send checksums to fix this properly, which would add a lot of overhead and complexity, and even when it happens, it's captured rather elegantly even if the MemoryError might be confusing (but the lost connection message is clear). I don't see how this could lead to any data corruption at the end of the day because there are checksums at the file level (not at the data chunk level though).

For all these more or less good reason, I close the issue. Thanks for reporting it and don't hesitate to re-open it if you disagree with my analysis.

**Closed** 2020-06-18 07:31 UTC
Labels: bug, invalid

**Comment by olberger** [comment] 2020-12-10 12:13
FWIW, I've experienced the same issue whenever trying to connect over SSH (with a password-less key) on the destination, at a time when the login to the remote account was disabled. SSH connection was refused, which lead to that strange error.

Hth
