### ISSUE TITLE
[BUG] rdiff-backup 1.2.8 (Debian) fails to back up a version 2.0.0 (Ubuntu 20.04) client

### ISSUE THREAD

**Issue by ascheman** [rdiff-backup/rdiff-backup#513] opened 2021-01-07 08:47 UTC
## Bug summary

When I run `rdiff-backup` on my Debian 10 machine against an Ubuntu 20.04 remote machine I see the following error:

```
Exception ''version'' raised of class '<type 'exceptions.KeyError'>':
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 304, in error_check_Main
    try: Main(arglist)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 321, in Main
    rps = map(SetConnections.cmdpair2rp, cmdpairs)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/SetConnections.py", line 76, in cmdpair2rp
    if cmd: conn = init_connection(cmd)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/SetConnections.py", line 152, in init_connection
    check_connection_version(conn, remote_cmd)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/SetConnections.py", line 160, in check_connection_version
    try: remote_version = conn.Globals.get('version')
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/connection.py", line 450, in __call__
    return apply(self.connection.reval, (self.name,) + args)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/connection.py", line 370, in reval
    if isinstance(result, Exception): raise result

Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 30, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 304, in error_check_Main
    try: Main(arglist)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 321, in Main
    rps = map(SetConnections.cmdpair2rp, cmdpairs)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/SetConnections.py", line 76, in cmdpair2rp
    if cmd: conn = init_connection(cmd)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/SetConnections.py", line 152, in init_connection
    check_connection_version(conn, remote_cmd)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/SetConnections.py", line 160, in check_connection_version
    try: remote_version = conn.Globals.get('version')
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/connection.py", line 450, in __call__
    return apply(self.connection.reval, (self.name,) + args)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/connection.py", line 370, in reval
    if isinstance(result, Exception): raise result
KeyError: 'version'
```

## Version, Python, Operating System

Call `rdiff-backup --version --api-version 201` or `rdiff-backup -v9` and replace the following line with the output, repeat for each environment impacted:

Warning: Neither of the two installations understood the `--api-version 201` CLI parameter!

### Ubuntu 20.04

```
2021-01-07 09:36:24.254100 +0100  <CLIENT-2828914>  Using rdiff-backup version 2.0.0
2021-01-07 09:36:24.254190 +0100  <CLIENT-2828914>      with cpython /usr/bin/python3 version 3.8.5
2021-01-07 09:36:24.263109 +0100  <CLIENT-2828914>      on Linux-5.4.0-54-generic-x86_64-with-glibc2.29, fs encoding utf-8
2021-01-07 09:36:24.263200 +0100  <CLIENT-2828914>  Fatal Error: No arguments given
```

### Debian 10

```
Thu Jan  7 09:36:57 2021  Using rdiff-backup version 1.2.8
Thu Jan  7 09:36:57 2021  Fatal Error: No arguments given
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
rdiff-backup --print-statistics --remote-schema 'ssh -i ~/.ssh/xxx -C %s rdiff-backup --server' --exclude-special-files --exclude-filelist linux-generic-exclude root@target::/ backupdir
```

## What happened and what did you expect?

Expected proper backup as with version 1.2.8 before the Ubuntu upgrade.

## More information

```
Thu Jan  7 09:43:36 2021  Using rdiff-backup version 1.2.8
Thu Jan  7 09:43:36 2021  Executing ssh -i ... --server
Thu Jan  7 09:43:36 2021  Client sending (0): ConnectionRequest: Globals.get with 1 arguments
Thu Jan  7 09:43:36 2021  Client sending (0): 'version'
Thu Jan  7 09:43:37 2021  Client received (0): 'version'
Thu Jan  7 09:43:37 2021  Exception ''version'' raised of class '<type 'exceptions.KeyError'>':
...
```

**Comment by ascheman** [comment] 2021-01-07 08:58
Even upgrading to 2.0.5 on the Ubuntu machine did not resolve the problem.

**Comment by ascheman** [comment] 2021-01-07 09:12
Falling back to the legacy version 1.3.3 solved my problem now:

```
apt install rdiff-backup=1.3.3-1~ubuntu20.04.1~1587201466.6f71f76
```

**Comment by frankcrawford** [comment] 2021-01-07 11:48
@ascheman This is a known issue and caused by difference between python 2 used for rdiff-backup v1.2/1.3 and python 3 used for rdiff-backup 2 and on.
The are a number of methods discussed as work-arounds for this issue, but primarily they revolve around running both versions on your backup server, and choosing the correct version for the client you are backing up.

**Comment by ascheman** [comment] 2021-01-07 13:30
Thanks for your feedback, @frankcrawford. I could not find any issue related to this, can you provide any reference? 
I hope the raised issue will now make others aware of the (known) problem and my workaround.

**Comment by frankcrawford** [comment] 2021-01-09 05:37
@ascheman You are right, they are now hard to find as much of the discussion is now over a year old.  Two closed issues #436 and #161 covers some of it.

The plans to how to handle it in your own environment is probably more on the mailing list, and there is an outstanding request for this to be properly documented.

Have you looked at the (incomplete) https://github.com/rdiff-backup/rdiff-backup/blob/master/docs/migration.md ?
Also check https://lists.nongnu.org/archive/html/rdiff-backup-users/2020-04/msg00013.html from and some other discussions in the mailing list?

I guess what you have raised is that we need to clean up the migration doc, in particular with how to handle this incompatibility between the old and new versions of rdiff-backup.

**Comment by ascheman** [comment] 2021-01-09 15:48
Thanks, @frankcrawford, I have found my workaround: https://github.com/rdiff-backup/rdiff-backup/issues/513#issuecomment-755987789 - will not drive this topic any longer in the moment. Nevertheless, I would appreciate a solution in the long run since there are more clients to change to newer versions (>= 2.x) of rdiff-backup in the future. I will be happy to test or proof read your docs if you make any progress.

**Comment by ericzolf** [comment] 2021-01-10 10:39
I have linked the migration doc with the readme and added a clear warning about incompatibility, that should be enough to close this issue.

**Comment by ericzolf** [comment] 2021-01-10 12:06
In case I wasn't clear enough (I wasn't, I know :smirk: ): if nobody complains, I'll merge the PR and close the issue...

**Closed** 2021-01-17 08:43 UTC

**Comment by martinderm** [comment] 2021-05-14 12:27
Sorry for the possibly stupid questien, but how do I force downgrade to 1.2 or 1.2? on Ubuntu 20.4?
2.0 is not yet availiable on my other systems. 

I tried the following in different variations:

```
apt install rdiff-backup=1.3.3-1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '1.3.3-1' for 'rdiff-backup' was not found
```

**Comment by ericzolf** [comment] 2021-05-14 13:28
I don't think there is any simple way to do so. You could install 2.0 on your other systems using pip, but 1.2/1.3 hasn't been packaged for pip. You could only use the git repo and install from there.

**Comment by martinderm** [comment] 2021-05-14 13:33
Thx, so upgrading to 2.x will be it then...
