### ISSUE TITLE
CIFS filesystem with symbolic links

### ISSUE THREAD

**Issue by Zitrax** [rdiff-backup/rdiff-backup#12] opened 2016-10-14 13:42 UTC
I am mounting a windows drive using cifs and try to use rdiff-backup from a linux machine to the cifs mount.

If there are no symbolic links this works fine, but with links I get:

```
OSError: [Errno 95] Operation not supported
```

from rpath.py:1002 ( `self.conn.os.symlink(linktext, self.path)` ).

Also works fine if I pass `--exclude-symbolic-links` ofc.

After some googling I found an old [bug #20342: fails backing up to cifs share](http://savannah.nongnu.org/bugs/?20342) on savannah that seemed to fix the same or a similar problem. That fix seem to be cd2cb0a6 in git.

But that was back in 2007 - any idea of the current status regarding this,  should this work now ? ( I am using rdiff-backup 1.2.8 )

**Comment by ottok** [comment] 2020-02-16 09:36
Hello @Zitrax!

The code base has been rewritten for Python 3 and there will be no further releases for the 1.x series in Python 2 anymore. Could you please help our efforts and test again with the latest development version (https://github.com/rdiff-backup/rdiff-backup#installing-the-latest-development-version) if you can still reproduce this and provide us with a test case (steps on how to reproduce the issue) that applies for latest development version?

With your help, if we can reproduce this problem still with the 2.x code base if might be fixed it in upcoming 2.x series releases.

**Comment by Zitrax** [comment] 2020-02-17 23:00
Hi, sorry but this was an issue in a former job - I no longer have access to that setup.

**Comment by ikus060** [comment] 2020-02-18 00:48
@Zitrax Do you have a contact you can refer to us then ?

**Comment by Zitrax** [comment] 2020-02-18 12:43
> @Zitrax Do you have a contact you can refer to us then?

The company does no longer exist so unfortunately not.

**Comment by ikus060** [comment] 2020-02-18 12:46
Closing this issue since we don't have enough information.

**Closed by ikus060** 2020-02-18 12:46 UTC
Labels: enhancement
