### ISSUE TITLE
Files resulting as changed after swapping disks

### ISSUE THREAD

**Issue by th3bucch** [rdiff-backup/rdiff-backup#615] opened 2021-08-10 20:14 UTC
Hello,
hope it's legit to ask here for some help since i'm not aware of any support forum or community to ask to.

I'm using rdiff-backup to clone a data folder on my PC (Ubuntu 20.04 - rdiff-backup v2.0.0) to my NAS (Debian testing - rdiff-backup v2.0.5 ) via ssh. I set up a script to manually run the backup or just compare the source dir to the remote dir. It was working fine.

Today I swapped the disk on my PC where the data is, from an NTFS HDD to an ext4 SSD upon which i copied all the files keeping the same folder and file structure. I only changed the mount point.

Now, if i compare source and backup with
`rdiff-backup --compare --print-statistics --ssh-no-compression [new source dir] user@ip::[old dest dir]`
all files result as "changed" so i'm afraid if I will launch a new backup will overwrite everything, taking way longer than a simple incremental update.
Here's the properties of a random file with `stat` command and only difference is "access" (Accesso) and "change" (Cambio) timestamps.

**New source:**
> File: songs.txt
>   Dim.: 503       	Blocchi: 8          Blocco di IO: 4096   file regolare
> Device: 811h/2065d	Inode: 20452310    Coll.: 1
> Accesso: (0755/-rwxr-xr-x)  Uid: ( 1000/   bucch)   Gid: ( 1000/   bucch)
> Accesso  : 2021-08-10 18:04:03.287797000 +0200
> Modifica : 2015-09-19 21:13:14.535415000 +0200
> Cambio   : 2021-08-10 18:04:03.287797991 +0200

**Latest backup:**
> File: songs.txt
>   Dim.: 503       	Blocchi: 8          Blocco di IO: 1048576 file regolare
> Device: 38h/56d	Inode: 85067675    Coll.: 1
> Accesso: (0755/-rwxr-xr-x)  Uid: ( 1000/   bucch)   Gid: ( 1000/   bucch)
> Accesso  : 2020-05-03 13:22:57.000000000 +0200
> Modifica : 2015-09-19 21:13:14.000000000 +0200
> Cambio   : 2015-09-19 21:13:14.000000000 +0200
> Creazione: -

Is the software using the "change" timestamp of the files to do the comparison thus requiring me to backup the full data or there's some workaround I can use to quickly sync the folders?

Thanks

**Comment by ericzolf** [comment] 2021-08-11 06:21
It is legit but you might get more help for this kind of issue on the mailing list: https://lists.nongnu.org/mailman/listinfo/rdiff-backup-users (it's documented on our homepage).

First, as a side remark, `--print-statistics` doesn't change anything here.

Having the full version of the software would also help to make sure we're not talking about and old version.

Now to your point: the issue isn't the timestamp because rdiff-backup stores and cares only about the modification time (at the seconds level), not access or change time. So there must be something else different, possibly because copied between file systems of different type.

Could you check for the _latest_ metadata file in the repo, e.g. `zless rdiff-backup-data/mirror_metadata.2021-08-11T07\:52\:30+02\:00.xxx.gz` and then search there for this songs.txt file and copy here its section. If the file isn't in the latest diff, take the next older, etc, until you find the correct file or you hit a snapshot file. In other words, call something like the following and inspect each file starting from the top until you find the songs.txt:

```
$ ls -1t /tmp/bak1/rdiff-backup-data/mirror_metadata.*
/tmp/bak1/rdiff-backup-data/mirror_metadata.2021-08-11T07:52:30+02:00.diff.gz
/tmp/bak1/rdiff-backup-data/mirror_metadata.2021-08-11T08:17:35+02:00.snapshot.gz
```

The section should look something like this:

```
File songs.txt
  Type reg
  Size 23497
  SHA1Digest bc50e10081320c921edcc4cfa4ad875bdd687eac
  ModTime 1623389920
  Uid 1000
  Uname ericl
  Gid 1000
  Gname ericl
  Permissions 436
```

**Comment by th3bucch** [comment] 2021-08-11 10:09
Hi, thanks for pointing me to the mailing list, i must have missed it. Next time i will ask there.

Software version as output from `rdiff-backup --version` is the same I posted above which is 2.0.0 on Ubuntu source and 2.0.5 on Debian server.

I found the following in the latest snapshot from yesterday just a couple of hours before the swap:

```
File Documenti/songs.txt
Type reg
Size 503
SHA1Digest a2252bd743588c81b846cb09a1a50929ec9c0807
ModTime 1442689994
Uid 1000
Uname bucch
Gid 0
Gname root
Permissions 493
```

**Comment by ericzolf** [comment] 2021-08-11 11:02
OK, everything looks the same with one exception: the Gid/Gname is 0/root instead of 1000/bucch. Verify that it's the case for all files, but given that you moved away from NTFS, I guess it is the case.

There are multiple ways to fix this, roughly from simple to complex:

1. apply `sudo chgrp -R root [new source dir]` to align the source with what's in your backup repo
2. just accept the fact that rdiff-backup will modify all the files and run one backup, it might take quite a lot of time but shouldn't take a lot of disk space, as only the metadata i.e. group ownership will change.
3. you could try to map 0/root to 1000/bucch using the `--group-mapping-file`. As I have no experience with this option, I'm not sure it will help, but it sounds like a candidate.
4. now for a (dangerous) hack: you could edit the last `mirror_metadata.xxx.diff.gz` files down and including the last `mirror_metadata.xxx.snapshot.gz` file and search and replace all the Gid/Gname entries... In Vim, something like `:%s/Gid 0$/Gid 1000/` resp. `:%s/Gname root$/Gname bucch/`. As said, do this only if you're desperate, absolutely understand what you're doing and won't complain if you corrupt your repository.

Last thing: sorry for missing the version information but you should upgrade 2.0.0 to 2.0.5, else you're missing five bugfix versions, that can be quite a lot... Check https://github.com/rdiff-backup/rdiff-backup#411-ubuntu-and-debian-development-releases

**Comment by ericzolf** [comment] 2021-08-11 11:13
OK, after some quick testing, the group-mapping-file would probably not help you, it does only map at the file system level, not what is stored in the metadata...

**Comment by ericzolf** [comment] 2022-01-02 13:31
So I understood that the issue is solved, I close it. Feel free to re-open it if you think otherwise.

**Closed by ericzolf** 2022-01-02 13:31 UTC
