### ISSUE TITLE
[BUG] 2.2.6 Unconditionally warns when api-version <= 200

### ISSUE THREAD

**Issue by northnose** [rdiff-backup/rdiff-backup#925] opened 2023-09-23 08:45 UTC
## Bug summary

 #910 adds a warning:

> WARNING: Server will be called with deprecated command line interface to guarantee compatibility. It might lead to a deprecation warning from newer rdiff-backup versions. Use '--api-version 201' (or higher) to avoid it.

There doesn't seem to be a way to silence this warning. Due to legacy setups (i.e. CentOS 7 which doesn't EOL until June 2024, but is on rdiff-backup 2.0.5), I cannot use `--api-version 201`, so the suggestion doesn't work.

Can you add a way to silence this error in this case?

## Version, Python, Operating System

On local system:
```
$ rdiff-backup info
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - /usr/bin/rdiff-backup
  - info
  parsed: null
  version: 2.2.6
python:
  executable: /usr/bin/python3
  name: cpython
  version: 3.11.5
system:
  fs_encoding: utf-8
  platform: Linux-6.4.15-200.fc38.x86_64-x86_64-with-glibc2.37
...
```

On remote system (Centos 7):
```
$ rdiff-backup info
Fatal Error: Switches missing or wrong number of arguments
See the rdiff-backup manual page for more information.

$ rdiff-backup --version
rdiff-backup 2.0.5
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
rdiff-backup -v 3 --api-version 200 backup [some --include and --exclude paths] user@remote::/ /path/to/local/dir > /dev/null
```

## What happened and what did you expect?
Expected: rdiff-backup syncs files successfully and no output is observed
Actual: Everything works but this warning is emitted

## More information

If you can, please repeat the action leading to the error, adding the option `-v9` and attach the output to this bug report.

**Comment by ericzolf** [comment] 2023-09-23 09:04
Duplicate of #922

**Closed by ericzolf** 2023-09-23 09:04 UTC
Labels: bug, duplicate

**Comment by northnose** [comment] 2023-09-23 09:18
@ericzolf #922 is about a local operation. This is about a remote operation where the remote does not support api version 201. Are you saying this is a wontfix and there will not be a way to silence this warning?

**Comment by ericzolf** [comment] 2023-09-23 09:34
Correct.
