### ISSUE TITLE
rdiff-backup long file names

### ISSUE THREAD

**Issue by kast88x** [rdiff-backup/rdiff-backup#235] opened 2020-01-09 12:15 UTC
hi all

I have a problem with a dayly backup:

```
Previous backup seems to have failed, regressing destination now.
Exception 'Path: /backup3/storage/office/srvmail1/home/rdiff-backup-data/long_filename_data/2.2019-12-24T02:45:00+04:00.dir
Index: ('long_filename_data', '2.2019-12-24T02:45:00+04:00.dir')
Data: {'acl': <rdiff_backup.eas_acls.AccessControlLists instance at 0x1b79dd0>, 'uid': 5268, 'perms': 448, 'type': 'reg', 'gname': None, 'ea': <rdiff_backup.eas_acls.ExtendedAttributes instance at 0x1b79f38>, 'ctime': 1577229357, 'devloc': 2048L, 'uname': None, 'nlink': 1, 'gid': 1003, 'mtime': 1577134505, 'atime': 1577229357, 'inode': 79345391, 'size': 0}' raised of class '<type 'exceptions.AssertionError'>':
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/Main.py", line 304, in error_check_Main
    try: Main(arglist)
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/Main.py", line 324, in Main
    take_action(rps)
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/Main.py", line 280, in take_action
    elif action == "backup": Backup(rps[0], rps[1])
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/Main.py", line 343, in Backup
    backup.Mirror_and_increment(rpin, rpout, incdir)
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/backup.py", line 51, in Mirror_and_increment
    DestS.patch_and_increment(dest_rpath, source_diffiter, inc_rpath)
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/backup.py", line 243, in patch_and_increment
    ITR(diff.index, diff)
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/rorpiter.py", line 284, in __call__
    branch.start_process(*args)
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/backup.py", line 721, in start_process
    inc = increment.Increment(diff_rorp, self.base_rp, inc_prefix)
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/increment.py", line 41, in Increment
    elif mirror.isdir(): incrp = makedir(mirror, incpref)
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/increment.py", line 103, in makedir
    dirsign = get_inc(incpref, "dir")
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/increment.py", line 123, in get_inc
    assert not incrp.lstat(), incrp

Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 30, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/Main.py", line 304, in error_check_Main
    try: Main(arglist)
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/Main.py", line 324, in Main
    take_action(rps)
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/Main.py", line 280, in take_action
    elif action == "backup": Backup(rps[0], rps[1])
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/Main.py", line 343, in Backup
    backup.Mirror_and_increment(rpin, rpout, incdir)
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/backup.py", line 51, in Mirror_and_increment
    DestS.patch_and_increment(dest_rpath, source_diffiter, inc_rpath)
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/backup.py", line 243, in patch_and_increment
    ITR(diff.index, diff)
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/rorpiter.py", line 284, in __call__
    branch.start_process(*args)
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/backup.py", line 721, in start_process
    inc = increment.Increment(diff_rorp, self.base_rp, inc_prefix)
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/increment.py", line 41, in Increment
    elif mirror.isdir(): incrp = makedir(mirror, incpref)
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/increment.py", line 103, in makedir
    dirsign = get_inc(incpref, "dir")
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/increment.py", line 123, in get_inc
    assert not incrp.lstat(), incrp
AssertionError: Path: /backup3/storage/office/srvmail1/home/rdiff-backup-data/long_filename_data/2.2019-12-24T02:45:00+04:00.dir
Index: ('long_filename_data', '2.2019-12-24T02:45:00+04:00.dir')
Data: {'acl': <rdiff_backup.eas_acls.AccessControlLists instance at 0x1b79dd0>, 'uid': 5268, 'perms': 448, 'type': 'reg', 'gname': None, 'ea': <rdiff_backup.eas_acls.ExtendedAttributes instance at 0x1b79f38>, 'ctime': 1577229357, 'devloc': 2048L, 'uname': None, 'nlink': 1, 'gid': 1003, 'mtime': 1577134505, 'atime': 1577229357, 'inode': 79345391, 'size': 0}
```

After running rdiff-backup --check-destination-dir I can list the backups using rdiff-backup -l but next backups also fall out with the above error

found a patch that fixes this error:
https://build.opensuse.org/package/view_file/openSUSE:Factory/rdiff-backup/rdiff-backup-1.2.8-sparsefiles.diff?expand=1

edited the file /usr/lib64/python2.7/site-packages/rdiff_backup/rpath.py, but it didn’t help, maybe I’m doing something wrong ?

how to fix it?
thanx

**Comment by ericzolf** [comment] 2020-01-11 16:37
I don't see how the patch could fix your issue as it's about using sparse files to store efficiently specific files, and might more introduce issues than fix any.

For now assuming that your issue is a duplicate of "Regression of failed backup with long file names can result in assertion error #9" and closing. It'll be one of the next bugs we'll fixed after the current release is out.

**Closed** 2020-01-11 16:38 UTC
