### ISSUE TITLE
[BUG] Crash on network drive due to handling too specific exceptions

### ISSUE THREAD

**Issue by JirkaV** [rdiff-backup/rdiff-backup#384] opened 2020-05-28 14:24 UTC
## Bug summary

I have a home NAS (WD MyCloud) and Windows 10 PC connected to it via regular network sharing. When I try to backup to that destination, rdiff-backup crashes. I'll submit a pull request shortly.

## Version, Python, Operating System

Call `rdiff-backup -v9` and paste the output between the backquotes below, repeat for each environment impacted:

```
```

## rdiff-backup call

How did you call rdiff-backup, with which parameter:

```
D:\Fotky\Export\pro_Pavla>python "C:\Program Files (x86)\Python37-32\Scripts\rdiff-backup" --force -v5 --no-acls --exclude "C:/Lightroom Catalog/Lightroom Catalog Previews.lrdata" --exclude "*Smart*" --exclude "**.lrprev" --exclude "**.lrfprev" --exclude "**.dng" "C:/Lightroom Catalog/" "X:/Lightroom Catalog Backup Test/"
Using rdiff-backup version 2.0.3
        with cpython C:\Program Files (x86)\Python37-32\python.exe version 3.7.7
        on Windows-10-10.0.18362-SP0, fs encoding utf-8
Hardlinks disabled by default on Windows
Unable to import module (py)xattr.
Extended attributes not supported on filesystem at C:/Lightroom Catalog
POSIX ACLs test skipped. rdiff-backup run with --no-acls option.
Windows ACLs test skipped. rdiff-backup run with --no-acls option.
-----------------------------------------------------------------
Detected abilities for source (read only) file system:
  Access control lists                         Off
  Extended attributes                          Off
  Windows access control lists                 Off
  Case sensitivity                             Off
  Escape DOS devices                           On
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
Directories on file system at X:/Lightroom Catalog Backup Test/rdiff-backup-data/rdiff-backup.tmp.0 are not fsyncable.
Assuming it's unnecessary.
Unable to import module (py)xattr.
Extended attributes not supported on filesystem at X:/Lightroom Catalog Backup Test/rdiff-backup-data/rdiff-backup.tmp.0
POSIX ACLs test skipped. rdiff-backup run with --no-acls option.
Windows ACLs test skipped. rdiff-backup run with --no-acls option.
Exception '[WinError 6] The handle is invalid: b'X:/Lightroom Catalog Backup Test/rdiff-backup-data/rdiff-backup.tmp.0/foo.'' raised of class '<class 'OSError'>':
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\Main.py", line 393, in error_check_Main
    Main(arglist)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\Main.py", line 415, in Main
    take_action(rps)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\Main.py", line 351, in take_action
    Backup(rps[0], rps[1])
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\Main.py", line 427, in Backup
    rpout.conn.fs_abilities.backup_set_globals(rpin, force)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\fs_abilities.py", line 1044, in backup_set_globals
    dest_fsa = FSAbilities('destination').init_readwrite(Globals.rbdir)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\fs_abilities.py", line 172, in init_readwrite
    self.set_escape_trailing_spaces_readwrite(subdir)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\fs_abilities.py", line 636, in set_escape_trailing_spaces_readwrite
    period_rp = testdir.append("foo.")
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\rpath.py", line 1412, in append
    return self.__class__(self.conn, self.base, self.index + ext)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\rpath.py", line 1082, in __init__
    self.setdata()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\rpath.py", line 1108, in setdata
    self.data = self.conn.rpath.make_file_dict(self.path)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\rpath.py", line 386, in make_file_dict
    statblock = os.lstat(filename)

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\Scripts\rdiff-backup", line 4, in <module>
    __import__('pkg_resources').run_script('rdiff-backup==2.0.3', 'rdiff-backup')
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "c:\program files (x86)\python37-32\lib\site-packages\rdiff_backup-2.0.3-py3.7-win32.egg\EGG-INFO\scripts\rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\Main.py", line 393, in error_check_Main
    Main(arglist)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\Main.py", line 415, in Main
    take_action(rps)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\Main.py", line 351, in take_action
    Backup(rps[0], rps[1])
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\Main.py", line 427, in Backup
    rpout.conn.fs_abilities.backup_set_globals(rpin, force)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\fs_abilities.py", line 1044, in backup_set_globals
    dest_fsa = FSAbilities('destination').init_readwrite(Globals.rbdir)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\fs_abilities.py", line 172, in init_readwrite
    self.set_escape_trailing_spaces_readwrite(subdir)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\fs_abilities.py", line 636, in set_escape_trailing_spaces_readwrite
    period_rp = testdir.append("foo.")
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\rpath.py", line 1412, in append
    return self.__class__(self.conn, self.base, self.index + ext)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\rpath.py", line 1082, in __init__
    self.setdata()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\rpath.py", line 1108, in setdata
    self.data = self.conn.rpath.make_file_dict(self.path)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\rpath.py", line 386, in make_file_dict
    statblock = os.lstat(filename)
OSError: [WinError 6] The handle is invalid: b'X:/Lightroom Catalog Backup Test/rdiff-backup-data/rdiff-backup.tmp.0/foo.'
```

## More information

If you can, please repeat the action leading to the error, adding the option `-v9` and attach the output to this bug report.

**Comment by JirkaV** [comment] 2020-06-04 15:17
OK, I'm at a loss. Don't know why is this happening as I can clearly do the same thing manually:
```
>>> with open('X:/Lightroom Catalog Backup Test/rdiff-backup-data/rdiff-backup.tmp.0/foo.', 'wb') as f:
...     f.write(b'test')
...
4
>>> filename = 'X:/Lightroom Catalog Backup Test/rdiff-backup-data/rdiff-backup.tmp.0/foo.'
>>> import os
>>> os.lstat(filename)
os.stat_result(st_mode=33206, st_ino=146071902, st_dev=3910445541, st_nlink=1, st_uid=0, st_gid=0, st_size=4, st_atime=1591283212, st_mtime=1591283500, st_ctime=1591283212)
>>>
```

Will debug a bit more and figure out the root cause.

**Comment by ericzolf** [comment] 2020-06-05 10:33
Has this happened once or can you reproduce it each time?

**Comment by JirkaV** [comment] 2020-06-05 10:52
It's reproducible, happens every time. Just tried.

**Comment by ericzolf** [comment] 2020-06-06 06:15
A few hints about what the code actually does:

- it uses bytes paths, that might make a difference, the Windows support isn't always perfect
- it tests first that b`.../foo.` (with dot) does _not_ exist
- then it creates b`.../foo` (without dot)
- and checks again if Windows thinks that b`.../foo.` (with dot) does exist, because FAT32 doesn't make the difference, it seems.

The code fails already at the first check, where no file exists.

**Comment by ericzolf** [comment] 2020-06-06 11:19
I definitely can't reproduce the issue:

```
vagrant@WIN-F6TA07RCPCE X:\Lightroom Catalog Backup Test\rdiff-backup-data>python
Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] on win32 
Type "help", "copyright", "credits" or "license" for more information.
>>> import os 
>>> filename = b'X:/Lightroom Catalog Backup Test/rdiff-backup-data/rdiff-backup.tmp.0/foo' 
>>> filename_dot = filename + b'.' 
>>> os.lstat(filename_dot) 
Traceback (most recent call last): 
  File "<stdin>", line 1, in <module>
FileNotFoundError: [WinError 2] The system cannot find the file specified: b'X:/Lightroom Catalog Backup Test/rdiff-backup-data/rdiff-backup.tmp.0/foo.'
>>> with open(filename, 'wb') as f: 
...   f.write(b'test') 
...  
4 
>>> os.lstat(filename_dot)     
os.stat_result(st_mode=33206, st_ino=25468660, st_dev=2841035209, st_nlink=1, st_uid=0, st_gid=0, st_size=4, st_atime=1591441881, st_mtime=1591441894, st_ctime=1591441881)
```

The issue is that, instead of a file not found error, which is properly captured, you (probably) get an invalid handle error, which isn't. If you can confirm this with the above test, we could try to capture the exception as well.

**Comment by ericzolf** [comment] 2020-06-20 07:31
@JirkaV any news on this topic? Were you able to reproduce the issue with my instructions?

**Comment by JirkaV** [comment] 2020-06-23 09:24
Not yet, sorry. I still want to help fix/resolve this, but I'm currently
extremely busy. Will update when I can.

  Jirka

**Comment by JirkaV** [comment] 2020-06-25 19:26
Here is my manual test:
```
C:\>python
Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 09:44:33) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> filename = b'X:/Lightroom Catalog Backup Test/rdiff-backup-data/rdiff-backup.tmp.0/foo'
>>> filename_dot = filename + b'.'
>>> os.lstat(filename_dot)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [WinError 2] The system cannot find the file specified: b'X:/Lightroom Catalog Backup Test/rdiff-backup-data/rdiff-backup.tmp.0/foo.'
>>> with open(filename, 'wb') as f:
...     f.write(b'test')
...
4
>>> os.lstat(filename_dot)
os.stat_result(st_mode=33206, st_ino=146068216, st_dev=3910445541, st_nlink=1, st_uid=0, st_gid=0, st_size=4, st_atime=1593113104, st_mtime=1593113104, st_ctime=1593113104)
>>>
```

**Comment by JirkaV** [comment] 2020-06-25 19:29
However, when running the regular backup:
```
C:\>python "C:\Program Files (x86)\Python37-32\Scripts\rdiff-backup" --force -v5 --no-acls --exclude "C:/Lightroom Catalog/Lightroom Catalog Previews.lrdata" --exclude "*Smart*" --exclude "**.lrprev" --exclude "**.lrfprev" --exclude "**.dng" "C:/Lightroom Catalog/" "X:/Lightroom Catalog Backup Test/"
Using rdiff-backup version 2.0.3
        with cpython C:\Program Files (x86)\Python37-32\python.exe version 3.7.7
        on Windows-10-10.0.18362-SP0, fs encoding utf-8
Hardlinks disabled by default on Windows
Unable to import module (py)xattr.
Extended attributes not supported on filesystem at C:/Lightroom Catalog
POSIX ACLs test skipped. rdiff-backup run with --no-acls option.
Windows ACLs test skipped. rdiff-backup run with --no-acls option.
-----------------------------------------------------------------
Detected abilities for source (read only) file system:
  Access control lists                         Off
  Extended attributes                          Off
  Windows access control lists                 Off
  Case sensitivity                             Off
  Escape DOS devices                           On
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
Directories on file system at X:/Lightroom Catalog Backup Test/rdiff-backup-data/rdiff-backup.tmp.0 are not fsyncable.
Assuming it's unnecessary.
Unable to import module (py)xattr.
Extended attributes not supported on filesystem at X:/Lightroom Catalog Backup Test/rdiff-backup-data/rdiff-backup.tmp.0
POSIX ACLs test skipped. rdiff-backup run with --no-acls option.
Windows ACLs test skipped. rdiff-backup run with --no-acls option.
Exception '[WinError 6] The handle is invalid: b'X:/Lightroom Catalog Backup Test/rdiff-backup-data/rdiff-backup.tmp.0/foo.'' raised of class '<class 'OSError'>':
  File "C:\tools\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\Main.py", line 393, in error_check_Main
    Main(arglist)
  File "C:\tools\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\Main.py", line 415, in Main
    take_action(rps)
  File "C:\tools\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\Main.py", line 351, in take_action
    Backup(rps[0], rps[1])
  File "C:\tools\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\Main.py", line 427, in Backup
    rpout.conn.fs_abilities.backup_set_globals(rpin, force)
  File "C:\tools\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\fs_abilities.py", line 1044, in backup_set_globals
    dest_fsa = FSAbilities('destination').init_readwrite(Globals.rbdir)
  File "C:\tools\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\fs_abilities.py", line 172, in init_readwrite
    self.set_escape_trailing_spaces_readwrite(subdir)
  File "C:\tools\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\fs_abilities.py", line 636, in set_escape_trailing_spaces_readwrite
    period_rp = testdir.append("foo.")
  File "C:\tools\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\rpath.py", line 1412, in append
    return self.__class__(self.conn, self.base, self.index + ext)
  File "C:\tools\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\rpath.py", line 1082, in __init__
    self.setdata()
  File "C:\tools\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\rpath.py", line 1108, in setdata
    self.data = self.conn.rpath.make_file_dict(self.path)
  File "C:\tools\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\rpath.py", line 386, in make_file_dict
    statblock = os.lstat(filename)

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\Scripts\rdiff-backup", line 4, in <module>
    __import__('pkg_resources').run_script('rdiff-backup==2.0.3', 'rdiff-backup')
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "c:\tools\rdiff_backup-2.0.3-py3.7-win32.egg\EGG-INFO\scripts\rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "C:\tools\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\Main.py", line 393, in error_check_Main
    Main(arglist)
  File "C:\tools\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\Main.py", line 415, in Main
    take_action(rps)
  File "C:\tools\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\Main.py", line 351, in take_action
    Backup(rps[0], rps[1])
  File "C:\tools\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\Main.py", line 427, in Backup
    rpout.conn.fs_abilities.backup_set_globals(rpin, force)
  File "C:\tools\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\fs_abilities.py", line 1044, in backup_set_globals
    dest_fsa = FSAbilities('destination').init_readwrite(Globals.rbdir)
  File "C:\tools\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\fs_abilities.py", line 172, in init_readwrite
    self.set_escape_trailing_spaces_readwrite(subdir)
  File "C:\tools\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\fs_abilities.py", line 636, in set_escape_trailing_spaces_readwrite
    period_rp = testdir.append("foo.")
  File "C:\tools\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\rpath.py", line 1412, in append
    return self.__class__(self.conn, self.base, self.index + ext)
  File "C:\tools\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\rpath.py", line 1082, in __init__
    self.setdata()
  File "C:\tools\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\rpath.py", line 1108, in setdata
    self.data = self.conn.rpath.make_file_dict(self.path)
  File "C:\tools\rdiff_backup-2.0.3-py3.7-win32.egg\rdiff_backup\rpath.py", line 386, in make_file_dict
    statblock = os.lstat(filename)
OSError: [WinError 6] The handle is invalid: b'X:/Lightroom Catalog Backup Test/rdiff-backup-data/rdiff-backup.tmp.0/foo.'
```

**Comment by JirkaV** [comment] 2020-06-25 19:29
Wondering if it's some sort of a race condition...

**Comment by ericzolf** [comment] 2020-06-27 06:02
I'm looking at the code and I don't see how a race condition could occur, but something is necessarily different... Let me think about it, at the end of the day we might just need to ignore the WinError 6 but I don't like doing this kind of things without fully understanding what I'm doing.

**Comment by JirkaV** [comment] 2020-06-27 07:14
Sorry, I should have been clearer. I didn't mean race condition in your code, I meant somewhere in my home NAS device Samba handling...

**Comment by ericzolf** [comment] 2020-06-27 07:51
Could you give me the make of the Samba NAS device and/or the Samba parameters? Perhaps I can then reproduce the issue locally... I attach mine, perhaps it helps.

**Comment by ericzolf** [comment] 2020-06-27 07:59
And perhaps do a health-check on the disk and file system, just to make sure we're not hitting a stupid infrastructure error.

**Comment by ericzolf** [comment] 2021-06-07 19:57
One year without reaction, I allow myself to close the issue.

**Closed by ericzolf** 2021-06-07 19:57 UTC
Labels: need more info
