### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SwenSteinmann** [rdiff-backup/rdiff-backup#1008] opened 2024-06-12 15:30 UTC
## Bug summary

A long path throws a FileNotFountException. The backup process stops, the repository is faulty

## Version, Python, Operating System

```yaml
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - rdiff-backup
  - info
  parsed: null
  version: 2.2.5
python:
  executable: F:\proc\rdiff-backup-2.2.5-64\rdiff-backup.exe
  name: cpython
  version: 3.10.7
system:
  fs_encoding: utf-8
  platform: Windows-10-10.0.19045-SP0
...
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
F:\proc\rdiff-backup-2.2.5-64\rdiff-backup.exe --verbosity 4 --current-time 1718179141 backup --exclude-device-files --create-full-path --compression --no-acls --file-statistics  C:\Users\Swen F:\Rudi\Swen 
```

## What happened and what did you expect?

the backup process crashes and
```
Traceback (most recent call last):
  File "rdiffbackup\run.py", line 175, in <module>
  File "rdiffbackup\run.py", line 37, in main
  File "rdiffbackup\run.py", line 110, in main_run
  File "rdiffbackup\actions\backup.py", line 159, in run
  File "rdiff_backup\backup.py", line 39, in mirror_compat200
  File "rdiff_backup\backup.py", line 197, in patch
  File "rdiff_backup\rorpiter.py", line 146, in __call__
  File "rdiff_backup\backup.py", line 595, in fast_process_file
  File "rdiff_backup\longname.py", line 152, in get_mirror_inc_rps
  File "rdiff_backup\longname.py", line 135, in find_inc_pair
  File "rdiff_backup\longname.py", line 313, in _check_new_index
  File "rdiff_backup\longname.py", line 290, in wrap_call
  File "rdiff_backup\longname.py", line 306, in make_parent
  File "rdiff_backup\rpath.py", line 802, in makedirs
  File "os.py", line 225, in makedirs
FileNotFoundError: [WinError 206] Der Dateiname oder die Erweiterung ist zu lang: b'F:/Rudi/Swen/rdiff-backup-data/increments/AppData/Local/IsolatedStorage/fnuac3so.mga/vz0wwpoi.yy2/StrongName.1r34rtndphgwhqowmyxywu5guyuf1gh2/StrongName.bx0ds5js14qgmnal5bhexnafezsd5pyy/Files/LaunchDarkly_QUEtxzTz76Ad8h9-oQ6Z5qLlzl8ZwK6bWWpos3tjUh4='
[12044] Failed to execute script 'run' due to unhandled exception!
```

 the repository is faulty

```
**rdiff-backup.exe --verbosity 4 --current-time 1718179141 list increments --size F:\Rudi\Swen** 

Traceback (most recent call last):
  File "rdiffbackup\run.py", line 175, in <module>
  File "rdiffbackup\run.py", line 37, in main
  File "rdiffbackup\run.py", line 110, in main_run
  File "rdiffbackup\actions\list_.py", line 118, in run
  File "rdiffbackup\actions\list_.py", line 133, in _list_increments_sizes
  File "rdiffbackup\locations\repository.py", line 570, in get_increments_sizes
  File "rdiffbackup\locations\repository.py", line 553, in get_summary_triples
IndexError: list index out of range
[15824] Failed to execute script 'run' due to unhandled exception!
```

the tool can handle long path or
it will ignore path wich are too long or
it shortens the paths in an sophisticated way

## More information

```
...removed the access denied error from browser cache ...

Traceback (most recent call last):
  File "rdiffbackup\run.py", line 175, in <module>
  File "rdiffbackup\run.py", line 37, in main
  File "rdiffbackup\run.py", line 110, in main_run
  File "rdiffbackup\actions\backup.py", line 159, in run
  File "rdiff_backup\backup.py", line 39, in mirror_compat200
  File "rdiff_backup\backup.py", line 197, in patch
  File "rdiff_backup\rorpiter.py", line 146, in __call__
  File "rdiff_backup\backup.py", line 595, in fast_process_file
  File "rdiff_backup\longname.py", line 152, in get_mirror_inc_rps
  File "rdiff_backup\longname.py", line 135, in find_inc_pair
  File "rdiff_backup\longname.py", line 313, in _check_new_index
  File "rdiff_backup\longname.py", line 290, in wrap_call
  File "rdiff_backup\longname.py", line 306, in make_parent
  File "rdiff_backup\rpath.py", line 802, in makedirs
  File "os.py", line 225, in makedirs
FileNotFoundError: [WinError 206] Der Dateiname oder die Erweiterung ist zu lang: b'F:/Rudi/Swen/rdiff-backup-data/increments/AppData/Local/IsolatedStorage/fnuac3so.mga/vz0wwpoi.yy2/StrongName.1r34rtndphgwhqowmyxywu5guyuf1gh2/StrongName.bx0ds5js14qgmnal5bhexnafezsd5pyy/Files/LaunchDarkly_QUEtxzTz76Ad8h9-oQ6Z5qLlzl8ZwK6bWWpos3tjUh4='
[7436] Failed to execute script 'run' due to unhandled exception!
NOTE: Found interrupted initial backup in data directory F:/Rudi/Swen/rdiff-backup-data. Removing...
NOTE: Symbolic links excluded by default on Windows
NOTE: Starting mirror from source path C:/Users/Swen to destination path F:/Rudi/Swen
```

**Comment by ericzolf** [comment] 2024-06-13 06:00
Duplicate of #782

**Closed by ericzolf** 2024-06-13 06:00 UTC
Labels: bug, triage
