### ISSUE TITLE
[BUG] --check-destination fails: Can't mix strings and bytes in path components

### ISSUE THREAD

**Issue by llowrey** [rdiff-backup/rdiff-backup#367] opened 2020-05-19 01:45 UTC
## Bug summary

Backup server crashed mid-backup. When checking various destination dirs I get a big stack dump and the dir fails to be rendered clean. Repeated executions produce the same results.

Turns out to be triggered by operator error. See below.

## Version, Python, Operating System

OS: Fedora 32 x86_64
rdiff-backup-2.0.3-1.fc32.x86_64

```
$ rdiff-backup -v9
2020-05-18 21:29:11.587398 -0400  <CLIENT-48254>  Using rdiff-backup version 2.0.3
2020-05-18 21:29:11.587472 -0400  <CLIENT-48254>        with cpython /usr/bin/python3 version 3.8.2
2020-05-18 21:29:11.590605 -0400  <CLIENT-48254>        on Linux-5.6.10-300.fc32.x86_64-x86_64-with-glibc2.2.5, fs encoding utf-8
```

## rdiff-backup call

```
 rdiff-backup --check-destination --force --tempdir tmp some-backup-dir
```

## What happened and what did you expect?

This happened:

```
Warning: Access Control List file not found
Warning: Extended Attributes file not found
Exception 'Can't mix strings and bytes in path components' raised of class '<class 'TypeError'>':
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/robust.py", line 35, in check_common_error
    return function(*args)
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/restore.py", line 528, in get_fp
    current_fp = self.get_first_fp()
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/restore.py", line 568, in get_first_fp
    current_fp = tempfile.TemporaryFile()
  File "/usr/lib64/python3.8/tempfile.py", line 614, in TemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib64/python3.8/tempfile.py", line 247, in _mkstemp_inner
    file = _os.path.join(dir, pre + name + suf)
  File "/usr/lib64/python3.8/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib64/python3.8/genericpath.py", line 155, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None

Exception 'Can't mix strings and bytes in path components' raised of class '<class 'TypeError'>':
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/Main.py", line 393, in error_check_Main
    Main(arglist)
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/Main.py", line 415, in Main
    take_action(rps)
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/Main.py", line 355, in take_action
    CheckDest(rps[0])
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/Main.py", line 1073, in CheckDest
    dest_rp.conn.regress.Regress(dest_rp)
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/regress.py", line 71, in Regress
    ITR(rf.index, rf)
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/rorpiter.py", line 313, in __call__
    last_branch.fast_process(*args)
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/regress.py", line 295, in fast_process
    self.restore_orig_regfile(rf)
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/regress.py", line 326, in restore_orig_regfile
    rf.mirror_rp.write_from_fileobj(rf.get_restore_fp())
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/restore.py", line 558, in get_restore_fp
    return robust.check_common_error(error_handler, get_fp)
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/robust.py", line 35, in check_common_error
    return function(*args)
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/restore.py", line 528, in get_fp
    current_fp = self.get_first_fp()
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/restore.py", line 568, in get_first_fp
    current_fp = tempfile.TemporaryFile()
  File "/usr/lib64/python3.8/tempfile.py", line 614, in TemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib64/python3.8/tempfile.py", line 247, in _mkstemp_inner
    file = _os.path.join(dir, pre + name + suf)
  File "/usr/lib64/python3.8/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib64/python3.8/genericpath.py", line 155, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None

Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/Main.py", line 393, in error_check_Main
    Main(arglist)
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/Main.py", line 415, in Main
    take_action(rps)
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/Main.py", line 355, in take_action
    CheckDest(rps[0])
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/Main.py", line 1073, in CheckDest
    dest_rp.conn.regress.Regress(dest_rp)
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/regress.py", line 71, in Regress
    ITR(rf.index, rf)
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/rorpiter.py", line 313, in __call__
    last_branch.fast_process(*args)
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/regress.py", line 295, in fast_process
    self.restore_orig_regfile(rf)
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/regress.py", line 326, in restore_orig_regfile
    rf.mirror_rp.write_from_fileobj(rf.get_restore_fp())
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/restore.py", line 558, in get_restore_fp
    return robust.check_common_error(error_handler, get_fp)
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/robust.py", line 35, in check_common_error
    return function(*args)
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/restore.py", line 528, in get_fp
    current_fp = self.get_first_fp()
  File "/usr/lib64/python3.8/site-packages/rdiff_backup/restore.py", line 568, in get_first_fp
    current_fp = tempfile.TemporaryFile()
  File "/usr/lib64/python3.8/tempfile.py", line 614, in TemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib64/python3.8/tempfile.py", line 247, in _mkstemp_inner
    file = _os.path.join(dir, pre + name + suf)
  File "/usr/lib64/python3.8/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib64/python3.8/genericpath.py", line 155, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
```
I expected the check to complete without error.

## More information

Tuns out that I typo'd the `--tempdir` argument and the dir I specified did not exist. When I fixed the dir the check worked as expected. Looks like `--tempdir` needs to check that the specified argument is really a dir (and hopefully writable).

**Comment by ericzolf** [comment] 2020-05-19 04:49
OK, it's a bug, thanks for reporting, we'll fix it in due time.

**Comment by ericzolf** [comment] 2020-05-20 11:41
In my opinion, it's actually more a bug in Python than in rdiff-backup but we'll workaround:

```
$ python
Python 3.8.2 (default, Feb 28 2020, 00:00:00) 
[GCC 10.0.1 20200216 (Red Hat 10.0.1-0.8)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tempfile
>>> tempfile.tempdir = b'/tmpxxx'
>>> tempfile.gettempdir()
b'/tmpxxx'
>>> tempfile.TemporaryFile()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.8/tempfile.py", line 614, in TemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib64/python3.8/tempfile.py", line 247, in _mkstemp_inner
    file = _os.path.join(dir, pre + name + suf)
  File "/usr/lib64/python3.8/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib64/python3.8/genericpath.py", line 155, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
>>> tempfile.tempdir = b'/tmp'
>>> tempfile.TemporaryFile()
<_io.BufferedRandom name=3>
```

Meaning that setting tempfile.tempdir to bytes only fails "ugly" if the directory doesn't exist. That's not very consistent.

**Comment by ericzolf** [comment] 2020-05-20 20:01
I've created a bug against python for this issue: https://bugs.python.org/issue40701 (my first one!)

Now I need to find the best workaround until the issue is fixed in Python.

**Comment by ericzolf** [comment] 2020-05-21 05:18
I won't create a new testcase for an error which happens only in case of previous error, but just for future reference, here is how to reproduce (the issue happens if a directory is transformed in a file or vice-versa):

```
mkdir /tmp/src{1,2}
date > /tmp/src1/file
mkdir /tmp/src2/file/
date > /tmp/src2/file/file2
mkdir /tmp/src1/dir
date > /tmp/src1/dir/file1
date > /tmp/src2/dir
rdiff-backup -v5 --current-time 10000 /tmp/src1 /tmp/bak1
rdiff-backup -v5 --current-time 20000 /tmp/src2 /tmp/bak1
touch /tmp/bak1/rdiff-backup-data/current_mirror.1970-01-01T03:46:40+01:00.data
rdiff-backup --check-destination --force --tempdir doesnotexist /tmp/bak1
```

**Comment by ericzolf** [comment] 2020-05-21 05:55
After I had fixed the bytes vs. string error, I noticed that the command succeeded even though the temporary directory didn't exist and did only output the following lines hinting at data loss:
```
Error reading b'/tmp/bak1/dir/file1', substituting empty file.
Error reading b'/tmp/bak1/file', substituting empty file.
```
So I added an explicit check that the tempfile does indeed exist and added a test for this exact case in #369

**Closed** 2020-05-21 18:40 UTC
Labels: bug
