### ISSUE TITLE
[BUG] Invalid cross-device link

### ISSUE THREAD

**Issue by ikus060** [rdiff-backup/rdiff-backup#1024] opened 2024-10-09 22:10 UTC
## Bug summary

rdiff-backup fail completly when trying to backup "fifo" from ext4 partition to ZFS dataset.

```
ERROR: Exception '[Errno 18] Invalid cross-device link: b'ikus060-rdiff/home/ikus060/workspace/PDSL/rdiff-backup.git/.tox/py/testfiles/compare_test/output/various_file_types/rdiff-backup.tmp.94585' -> b'ikus060-rdiff/home/ikus060/workspace/PDSL/rdiff-backup.git/.tox/py/testfiles/compare_test/output/various_file_types/fifo'' while renaming from path ikus060-rdiff/home/ikus060/workspace/PDSL/rdiff-backup.git/.tox/py/testfiles/compare_test/output/various_file_types/rdiff-backup.tmp.94585 to path ikus060-rdiff/home/ikus060/workspace/PDSL/rdiff-backup.git/.tox/py/testfiles/compare_test/output/various_file_types/fifo

WARNING: Exception '[Errno 18] Invalid cross-device link: b'ikus060-rdiff/home/ikus060/workspace/PDSL/rdiff-backup.git/.tox/py/testfiles/compare_test/output/various_file_types/rdiff-backup.tmp.94585' -> b'ikus060-rdiff/home/ikus060/workspace/PDSL/rdiff-backup.git/.tox/py/testfiles/compare_test/output/various_file_types/fifo'' raised of class '<class 'OSError'>':
  File "rdiff_backup/robust.py", line 94, in check_common_error
  File "rdiff_backup/rpath.py", line 1759, in rename

* Sending back exception '[Errno 18] Invalid cross-device link: b'ikus060-rdiff/home/ikus060/workspace/PDSL/rdiff-backup.git/.tox/py/testfiles/compare_test/output/various_file_types/rdiff-backup.tmp.94585' -> b'ikus060-rdiff/home/ikus060/workspace/PDSL/rdiff-backup.git/.tox/py/testfiles/compare_test/output/various_file_types/fifo'' of type <class 'OSError'> with traceback   File "rdiff_backup/connection.py", line 509, in _answer_request
  File "rdiff_backup/backup.py", line 210, in patch_and_increment
  File "rdiff_backup/rorpiter.py", line 146, in __call__
  File "rdiff_backup/backup.py", line 813, in fast_process_file
  File "rdiff_backup/robust.py", line 94, in check_common_error
  File "rdiff_backup/rpath.py", line 1759, in rename

* Cleaning up
OSError: [Errno 18] Invalid cross-device link: b'ikus060-rdiff/home/ikus060/workspace/PDSL/rdiff-backup.git/.tox/py/testfiles/compare_test/output/various_file_types/rdiff-backup.tmp.94585' -> b'ikus060-rdiff/home/ikus060/workspace/PDSL/rdiff-backup.git/.tox/py/testfiles/compare_test/output/various_file_types/fifo'
```

## Version, Python, Operating System

Call `rdiff-backup info` and replace the following line with the output,
repeat for each environment impacted, especially if using remote operations:

```yaml
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - minarca
  - rdiff-backup
  - info
  parsed: null
  version: 2.2.6
python:
  executable: /opt/minarca/minarca
  name: cpython
  version: 3.10.12
system:
  fs_encoding: utf-8
  platform: Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35
...
```

## rdiff-backup call

It's getting called from minarca. So N/A.

## What happened and what did you expect?

Since Cross-Device link are the kind of error that should be skip. I think we only need to add it to the list or robust error code.

## More information

N/A

**Comment by ericzolf** [comment] 2024-10-11 05:40
I got your explanations but it's still weird that renaming within the same directory and hence the same file system leads to such an error message. Are you sure it's not a generic issue with ZFS your file system (or a generic bug of the ZFS file system), in which case the signal shouldn't be ignored.

What happens if you call something like the following on this specific ZFS file system, and on another one? What if you do it with a normal file (fifo is a pipe file)? FYI, I can't reproduce the issue on an xfs file system.

```python
import os
os.rename('fifo', 'fifotest')
# or to be near to the actual code
os.rename(b'ikus060-rdiff/home/ikus060/workspace/PDSL/rdiff-backup.git/.tox/py/testfiles/compare_test/output/various_file_types/rdiff-backup.tmp.94585', b'ikus060-rdiff/home/ikus060/workspace/PDSL/rdiff-backup.git/.tox/py/testfiles/compare_test/output/various_file_types/fifo')
```

**Comment by ericzolf** [comment] 2024-10-11 05:43
Ah, and looking into the code, I find that we're already having a special handling for ZFS and errno.EXDEV in the `rpath.rename` function. It might be a better place to address this. But let's wait for you test results.

**Comment by ericzolf** [comment] 2024-10-12 07:30
I understand that you're trying to get ZFS working, but I really hesitate: this is a bug in the file system and this is where it should be fixed, not in rdiff-backup (I mean, the error message is nonsensical). Especially, ignoring the error could lead (on a normal file system) to ignoring an issue with the file system in its entirety and lead to a corrupt backup, which I won't accept.

**Comment by ikus060** [comment] 2024-10-16 14:22
> I understand that you're trying to get ZFS working, but I really hesitate: this is a bug in the file system and this is where it should be fixed, not in rdiff-backup (I mean, the error message is nonsensical).
> Especially, ignoring the error could lead (on a normal file system) to ignoring an issue with the file system in its entirety and lead to a corrupt backup, which I won't accept.

As I want rdiff-backup to be as reliable as possible, when a `Invalid cross-device link`, I don't expect rdiff-backup to completely fail and stop the backup. I would expect the error to be reported to the user and continue with the next file. That should be true with most exception getting raised that are specific to a single file.

In that scenario, this is the case. The fact this exception is raised doesn't prevent the backup to continue and only affect a single file. For that reason, I believe the error code should be added to the list of robust error code.

Also, getting more information about how this exception is handle by `mv`. (https://github.com/wertarbyte/coreutils/blob/master/src/mv.c). The code handle the scenario when renaming is not possible and fall back to copying instead. I believe rdiff-backup should do something similar. I event see the code in rdiff-backup where this is implemented `def rename` has a `try..except` block to fall back to `copy`. I think the same principle should be applied here.

**Comment by ericzolf** [comment] 2024-10-18 05:52
OK, I can live with this approach, but not with simply ignoring it. Do you adapt accordingly your PR?

**Comment by ikus060** [comment] 2024-10-18 11:53
> OK, I can live with this approach, but not with simply ignoring it. Do you adapt accordingly your PR?

Yes, I will work on a PR with this implementation. Thanks for your feedback

**Closed** 2024-11-17 17:18 UTC
Labels: bug, triage
