### ISSUE TITLE
[ENH] Support paths longer than 260 characters on Windows

### ISSUE THREAD

**Issue by xastor** [rdiff-backup/rdiff-backup#506] opened 2020-12-27 10:41 UTC
## Is your feature request related to a problem? Please describe.

The problem I experienced is that backing up to a Windows NTFS drive fails if paths are longer than 260 characters.  In this case, the backup completes without backing up the files with longer paths.  The fact that rdiff-backup escapes uppercase characters on a case-insensitive filesystem makes the problem manifest even quicker.

## Describe the solution you'd like

I would love rdiff-backup to support long paths on Windows.  This should be possible according to what I found : 
- https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation
- https://docs.python.org/3/using/windows.html#removing-the-max-path-limitation

## Describe alternatives you've considered

I tried setting the `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem@LongPathsEnabled` registry key to 1, as suggested in the articles above, but this did not have any apparent effect. 

As a quick workaround I tried to make the backup repo case-sensitive using the fsutil.exe utility : https://www.windowscentral.com/how-enable-ntfs-treat-folders-case-sensitive-windows-10

This did not work out because rdiff-backup does not detect the case-sensitivity.

## Additional context

I'm using Microsoft Windows [Version 10.0.18363.1256]

**Comment by ericzolf** [comment] 2020-12-27 10:59
We know :confounded: It's a duplicate of #236 
What confuses me though is that the Python documentation explicitly states "After changing the above option, no further configuration is required.", so I don't know what might be the exact problem here... I need to check but not my first priority right now, especially as it might be due to Python 3.7 not properly supporting byte paths, hence the need to upgrade Python under Windows first...

**Closed** 2020-12-27 11:01 UTC
Labels: duplicate
