### ISSUE TITLE
[ENH] option to preserve every nth backup older than a certain age

### ISSUE THREAD

**Issue by elMor3no** [rdiff-backup/rdiff-backup#748] opened 2022-09-27 03:49 UTC
Hello,

I am helping to package rdiff-backup for Debian. Reviewing the reported bugs [1] I found this request from a user.

> Package: rdiff-backup
> Version: 1.1.5-1
> Severity: wishlist
> 
> Maybe rdiff-backup could get an option so that it would skip
> deleting certain backups, even if they're too old. My theory is
> that I'd like to keep daily backups for the last 60 days, but
> anything older than that should be a monthly backup.
> 
> So if I backed up on 31 May, I would have backups for every day
> since April 1. When I back up on 1 June, it would *not* delete the
> backup for 1 April. If I back up on 2 June, it would delete the
> backup on 2 April. This way, the back up from 1 April stays around
> forever (until I manually delete it).

As the request implies changes in the operation of the project, I decided to report the request here.

You can find more details in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=370359
[1] https://bugs.debian.org/cgi-bin/pkgreport.cgi?src=rdiff-backup

**Comment by ericzolf** [comment] 2022-09-27 05:55
Duplicate of #560

**Closed by ericzolf** 2022-09-27 05:55 UTC
