### ISSUE TITLE
Does rdiff-backup intelligently handle log file rotation?

### ISSUE THREAD

**Issue by jsoref** [rdiff-backup/rdiff-backup#26] opened 2018-02-09 18:23 UTC
Some of our log files are *huge*, but right now I'm just looking at a simple case:
/var/log/letsencrypt/letsencrypt.log.N

Each time letsencrypt runs, it renames each file to N+1.

In a typical day, this will happen twice, which means files will move from N to N+2.

I suspect (but haven't traced) that rdiff-backup sees this as brand new data for each file.

Thankfully, letsencrypt's logs amount to about 5MB. OTOH, I have some log files that could easily be GBs large, and I'd be really sad if rdiff-backup had to resend all of them...

**Comment by ericzolf** [comment] 2019-08-11 06:47
You're right, rdiff-backup doesn't try to recognize renamed files, that would also be a huge change, and would introduce quite some delays to compare files in an intelligent manner. We could offer the possibility to steer it via command line, so I mark it as enhancement but don't hold your breath on this one.

**Comment by ottok** [comment] 2019-08-12 07:58
This is a general limitation in rsync/rdiff – it just compares file contents, not files and their locations, and thus does not detect renames/moves.

For this use case I suggest configuring logrotate to use the `dateext` configuration so that old log files keep the same name all the time.

**Comment by jsoref** [comment] 2019-08-12 11:12
In this case, there's no `logrotate`, just a default behavior of `letsencrypt` `certbot`.

**Comment by ericzolf** [comment] 2020-08-01 15:53
I don't see this enhancement coming any time soon so I just close it. Once we've addressed the more necessary/obvious issues, we might come back to it, but it might never happen. Sorry!

**Closed by ericzolf** 2020-08-01 15:53 UTC
Labels: enhancement, wontfix

**Comment by ericzolf** [comment] 2020-08-01 16:00
And additionally I realise that it's a duplicate of #68

**Comment by ottok** [comment] 2020-09-11 03:50
You shouldn't close issues too easily? Just document that you yourself will
not work on this in the foreseeable future, but contributions are welcome.
Unless, of course, you specifically don't want this feature.

**Comment by ericzolf** [comment] 2020-09-11 08:15
Anyway a duplicate of a still open bug but for the sake of the discussion: I don't think it helps a project to have too many issues, especially ones which aren't currently in the focus of the development. So do I want _today_ a new feature which will complicate the code base, the answer is clearly no.
