### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by brettk-git** [rdiff-backup/rdiff-backup#490] opened 2020-11-21 12:47 UTC
## Summary

Backing up directories with non-utf-8 names leads to error messages.

## Version, Python, Operating System

rdiff-backup version 2.0.5
with cpython /usr/bin/python3 version 3.8.6
on Linux-5.9.8-100.fc32.x86_64-x86_64-with-glibc2.2.5, fs encoding utf-8

## rdiff-backup call

mkdir in out; mkdir $(echo -e in/a\\\0340); rdiff-backup in out

(in a bash)

## What happened and what did you expect?

What happened:

Warning: unable to read default ACL from in/a�: 'utf-8' codec can't encode character '\udce0' in position 4: surrogates not allowed
Warning: unable to read default ACL from out/a�: 'utf-8' codec can't encode character '\udce0' in position 5: surrogates not allowed

What I expected:

No error message.

**Comment by ikus060** [comment] 2020-11-21 13:10
Nothing to do about this one. The pylibacl used to query the ACL on POSIX deosn't support surrogates. See https://github.com/iustin/pylibacl/issues/16

To get this fixed, would need to fix pylibacl ourself or find another library to get ACL for POSIX

**Comment by ericzolf** [comment] 2020-11-22 11:40
The issue isn't the name or the directory in itself, this gets backed-up and restored, the issue is only the ACL which can't be read, due to the library as Patrik wrote, so I would close the issue if nobody complains too loud.

**Comment by ericzolf** [comment] 2020-12-03 11:54
No reaction, then closing.

**Closed by ericzolf** 2020-12-03 11:54 UTC

**Comment by ikus060** [comment] 2020-12-08 18:38
@brettk-git Since https://github.com/iustin/pylibacl/issues/16 got fixed, you may re-try your scenarios and check if the ACL get properly saved with pylibacl >= 0.6.0
