### ISSUE TITLE
[BUG] Uppercase filenames backed up on FAT32 filesystem are escaped unnecessarily

### ISSUE THREAD

**Issue by hyperpenelope** [rdiff-backup/rdiff-backup#653] opened 2021-12-31 22:13 UTC
## Bug summary

When backing up a directory on to a FAT32 filesystem, uppercase letters ('A', 'B', 'C') in filenames are escaped (';065', ';066', ';067'). However, I can create filenames with uppercase letters - with `touch`, for example - and no escaping occurs. Thus the escaping behaviour of `rdiff-backup` appears to be unnecessary.

Escaping filenames in this way also causes filenames to become too long, which can cause backups to fail (seen before with #236).

## Version, Python, Operating System

```yaml
Operating system: Debian 10
Python3 version: 3.7.3
rdiff-backup version: 1.2.8
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```sh
# Create a directory on the main filesystem (ext4) and a file with a name containing uppercase letters.
mkdir src
touch src/ABC
# Create a directory on the FAT32-formatted partition
mkdir /media/myfatdrive/dest
# Back up with no special options
rdiff-backup src /media/myfatdrive/dest
```

## What happened and what did you expect?

**What happened** is that the following files appear in the destination dir on the FAT32 filesystem:
```
$ ls -l /media/myfatdrive/dest/
total 32K
drwxr-xr-x 3 user group 32K Dec 31 21:47  rdiff-backup-data
-rwxr-xr-x 1 user group   0 Dec 31 21:46 ';065;066;067'
```
The filename is literally `;065;066;067`; I can copy a file with that name off the FAT32 drive back to the main filesystem and, instead of being called `ABC` (its original name on the main filesystem), it is still called `;065;066;067`.

**What I expected** is what happens if I try to create a file called 'ABC' on the FAT32 drive using mundane methods, i.e.
```
$ touch /media/myfatdrive/anotherdir/ABC
$ ls -l /media/myfatdrive/anotherdir
total 0
-rwxr-xr-x 1 user group 0 Dec 31 21:50 ABC
```
The filename `ABC` does not appear to be escaped. Searching around the web, there is nothing to suggest that FAT32 filesystems cannot support uppercase Latin characters. So I would expect `rdiff-backup` to take advantage of this and not use escaping in this case.

## More information

If you can, please repeat the action leading to the error, adding the option `-v9` and attach the output to this bug report.

```
Fri Dec 31 22:03:28 2021  Using rdiff-backup version 1.2.8
Fri Dec 31 22:03:28 2021  Making directory /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data
Fri Dec 31 22:03:28 2021  Unable to import win32security module. Windows ACLs
not supported by filesystem at rdiff-backup-bug-src
Fri Dec 31 22:03:28 2021  escape_dos_devices not required by filesystem at rdiff-backup-bug-src
Fri Dec 31 22:03:28 2021  -----------------------------------------------------------------
Detected abilities for source (read only) file system:
  Access control lists                         On
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
Fri Dec 31 22:03:28 2021  Making directory /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0
Fri Dec 31 22:03:28 2021  Touching /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0/5-_ a.snapshot.gz
Fri Dec 31 22:03:28 2021  Deleting /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0/5-_ a.snapshot.gz
Fri Dec 31 22:03:28 2021  Touching /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0/uniᄉ
Fri Dec 31 22:03:28 2021  Deleting /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0/uniᄉ
Fri Dec 31 22:03:28 2021  Touching /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0/:\"
Fri Dec 31 22:03:28 2021  Touching /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0/A
Fri Dec 31 22:03:28 2021  Deleting /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0/a
Fri Dec 31 22:03:28 2021  Touching /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0/foo
Fri Dec 31 22:03:28 2021  Deleting /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0/foo
Fri Dec 31 22:03:28 2021  Making directory /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0/hl
Fri Dec 31 22:03:28 2021  Touching /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0/hardlinked_file1
Fri Dec 31 22:03:28 2021  Hard linking /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0/hl/hardlinked_file2 to /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0/hardlinked_file1
Fri Dec 31 22:03:28 2021  Warning: hard linking not supported by filesystem at /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data
Fri Dec 31 22:03:28 2021  Extended attributes not supported by filesystem at /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0
Fri Dec 31 22:03:28 2021  POSIX ACLs not supported by filesystem at /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0
Fri Dec 31 22:03:28 2021  Unable to import win32security module. Windows ACLs
not supported by filesystem at /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0
Fri Dec 31 22:03:28 2021  Touching /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0/dir_inc_check
Fri Dec 31 22:03:28 2021  Deleting /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0/dir_inc_check
Fri Dec 31 22:03:28 2021  Touching /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0/regfile
Fri Dec 31 22:03:28 2021  Deleting /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0/regfile
Fri Dec 31 22:03:28 2021  Touching /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0/high_perms_file
Fri Dec 31 22:03:28 2021  Touching /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0/high_perms_dir
Fri Dec 31 22:03:28 2021  Deleting /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0/high_perms_file
Fri Dec 31 22:03:28 2021  Deleting /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0/high_perms_dir
Fri Dec 31 22:03:28 2021  Touching /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0/symlinked_file1
Fri Dec 31 22:03:28 2021  Deleting /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0/symlinked_file1
Fri Dec 31 22:03:28 2021  escape_dos_devices not required by filesystem at /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0
Fri Dec 31 22:03:28 2021  Deleting /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0
Fri Dec 31 22:03:28 2021  Removing directory /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/rdiff-backup.tmp.0
Fri Dec 31 22:03:28 2021  -----------------------------------------------------------------
Detected abilities for destination (read/write) file system:
  Ownership changing                           Off
  Hard linking                                 N/A
  fsync() directories                          On
  Directory inc permissions                    Off
  High-bit permissions                         Off
  Symlink permissions                          Off
  Extended filenames                           On
  Windows reserved filenames                   On
  Access control lists                         Off
  Extended attributes                          Off
  Windows access control lists                 Off
  Case sensitivity                             Off
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
Fri Dec 31 22:03:28 2021  Backup: must_escape_dos_devices = 0
Fri Dec 31 22:03:28 2021  Making directory /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/increments
Fri Dec 31 22:03:28 2021  Starting mirror rdiff-backup-bug-src to /media/300-drive/rdiff-backup-bug-dest
Fri Dec 31 22:03:28 2021  Processing changed file .
Fri Dec 31 22:03:28 2021  Processing changed file ABC
Fri Dec 31 22:03:28 2021  Regular copying ('ABC',) to /media/300-drive/rdiff-backup-bug-dest/rdiff-backup.tmp.1
Fri Dec 31 22:03:28 2021  Writing file object to /media/300-drive/rdiff-backup-bug-dest/rdiff-backup.tmp.1
Fri Dec 31 22:03:28 2021  Copying attributes from ('ABC',) to /media/300-drive/rdiff-backup-bug-dest/rdiff-backup.tmp.1
Fri Dec 31 22:03:28 2021  Setting time of /media/300-drive/rdiff-backup-bug-dest/rdiff-backup.tmp.1 to 1640987181
Fri Dec 31 22:03:28 2021  Renaming /media/300-drive/rdiff-backup-bug-dest/rdiff-backup.tmp.1 to /media/300-drive/rdiff-backup-bug-dest/;065;066;067
Fri Dec 31 22:03:28 2021  Copying attributes from () to /media/300-drive/rdiff-backup-bug-dest
Fri Dec 31 22:03:28 2021  Setting time of /media/300-drive/rdiff-backup-bug-dest to 1640987181
Fri Dec 31 22:03:28 2021  Touching /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/extended_attributes.2021-12-31;08422;05803;05828;090.snapshot
Fri Dec 31 22:03:28 2021  Touching /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/access_control_lists.2021-12-31;08422;05803;05828;090.snapshot
Fri Dec 31 22:03:28 2021  Writing mirror marker /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/current_mirror.2021-12-31;08422;05803;05828;090.data
Fri Dec 31 22:03:28 2021  Cleaning up
Fri Dec 31 22:03:28 2021  Touching /media/300-drive/rdiff-backup-bug-dest/rdiff-backup-data/error_log.2021-12-31;08422;05803;05828;090.data
```

**Comment by ericzolf** [comment] 2022-01-01 09:15
You misunderstand what the problem is that the quoting addresses: on the source file system (assumed to be Posix, e.g. ext4 or xfs) you can have _multiple_ files with the same letters but different cases, for example "Abc" and "aBc". Without quoting, they couldn't exist side by side on a FAT filesystem and one would get lost.

The real test is to do `touch Abc; touch aBc` and see that only one file remains. Hence closing.

**Closed by ericzolf** 2022-01-01 09:15 UTC

**Comment by hyperpenelope** [comment] 2022-01-01 18:28
Thank you for the clarification! Sorry that this wasn't actually a bug.

**Comment by ericzolf** [comment] 2022-01-01 18:35
No issue, personally I'm _not_ sorry that this wasn't a bug :smirk: (sorry, I couldn't resist)
