### ISSUE TITLE
[BUG] files ending in <space> fail for ntfs target mounted as non-root

### ISSUE THREAD

**Issue by brainchild0** [rdiff-backup/rdiff-backup#579] opened 2021-05-12 13:17 UTC
# Bug summary

Linux file systems (e.g. Btrfs) support file names ending in a space (i.e. standard ASCII *space* character), but Windows (e.g. NTFS) apparently have no support, at least through the Linux drivers.

# Environment 

- Software versions:

   - **Application version:** rdiff-backup 2.0.6.dev22+g1ef7c45.ubuntu20.4.1
   - **Python version:** 3.8.5
   - **Operating system:** Linux Mint 20.1

- Output of `rdiff-backup -v9`:

```   
2021-05-12 09:00:32.016494 -0400  <CLIENT-21977>  Fatal Error: No arguments given
See the rdiff-backup manual page for more information.
2021-05-12 09:00:32.007390 -0400  <CLIENT-21977>  Using rdiff-backup version 2.0.6.dev22+g1ef7c45.ubuntu20.4.1
2021-05-12 09:00:32.007462 -0400  <CLIENT-21977>  	with cpython /usr/bin/python3 version 3.8.5
2021-05-12 09:00:32.016431 -0400  <CLIENT-21977>  	on Linux-5.8.0-53-generic-x86_64-with-glibc2.29, fs encoding utf-8
```

- Command invocation:

```
rdiff-backup call: `rdiff-backup --no-acl <linux_dir> <ntfs_target>`
```

# What happened 

Operation aborted with following error dump:

```
Exception '[Errno 22] Invalid argument: b'<srcdir>/ a ' raised of class '<class 'OSError'>':
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 399, in error_check_Main
    _Main(arglist)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 421, in _Main
    return_val = _take_action(rps)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 358, in _take_action
    action_result = _action_backup(rps[0], rps[1])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 448, in _action_backup
    backup.Mirror(rpin, rpout)
  File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 39, in Mirror
    DestS.patch(dest_rpath, source_diffiter)
  File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 269, in patch
    ITR(diff.index, diff)
  File "/usr/lib/python3/dist-packages/rdiff_backup/rorpiter.py", line 316, in __call__
    branch.start_process(*args)
  File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 708, in start_process
    self._prepare_dir(diff_rorp, self.base_rp)
  File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 742, in _prepare_dir
    base_rp.mkdir()
  File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 1200, in mkdir
    self.conn.os.mkdir(self.path)

Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 399, in error_check_Main
    _Main(arglist)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 421, in _Main
    return_val = _take_action(rps)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 358, in _take_action
    action_result = _action_backup(rps[0], rps[1])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 448, in _action_backup
    backup.Mirror(rpin, rpout)
  File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 39, in Mirror
    DestS.patch(dest_rpath, source_diffiter)
  File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 269, in patch
    ITR(diff.index, diff)
  File "/usr/lib/python3/dist-packages/rdiff_backup/rorpiter.py", line 316, in __call__
    branch.start_process(*args)
  File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 708, in start_process
    self._prepare_dir(diff_rorp, self.base_rp)
  File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 742, in _prepare_dir
    base_rp.mkdir()
  File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 1200, in mkdir
    self.conn.os.mkdir(self.path)
OSError: [Errno 22] Invalid argument: b'<srcdir>/ a '
```

# More information

During operations across types of file system, the application prints a large number of warnings, which have unclear significance to the integrity of the backup, and to other considerations. It may help users if messages gave clear indication of what problems to expect that may be associated with the  warnings, especially with respect to accurate restore.

**Comment by ericzolf** [comment] 2021-05-12 16:38
> * Command invocation:
> 
> ```
> rdiff-backup call: `rdiff-backup --no-acl <linux_dir> <ntfs_target>`
> ```

Is ntfs target a NTFS file system mounted  locally under Linux or a remote Winows target, something like `host::c:/backup`?

**Comment by ericzolf** [comment] 2021-05-12 16:40
> During operations across types of file system, the application prints a large number of warnings, which have unclear significance to the integrity of the backup, and to other considerations. It may help users if messages gave clear indication of what problems to expect that may be associated with the warnings, especially with respect to accurate restore.

You are most probably right but can you be more specific?

**Comment by brainchild0** [comment] 2021-05-12 18:31
> You are most probably right but can you be more specific?




Following is an example:

```
Warning: could not determine case sensitivity of source directory at
  <dirname>
because we can't find any files with letters in them.
It will be treated as case sensitive.
Warning: could not determine if source directory at
  <dirname>
permits trailing spaces or periods in filenames because we can't find any files.
It will be treated as permitting such files.
```

When on a FAT32 target   I saw a similar message about hard links. I no longer have a copy of the exact text, but I remember seeing no indication of how the issue would affect either the backup or the restore.

**Comment by ericzolf** [comment] 2021-05-15 05:17
I moved the improved warning messages to another issue. Let's focus on the trailing space issue...

For now, I can't reproduce it:

```
dd if=/dev/zero of=/tmp/ntfs.fs bs=4096 count=10240
mkfs.ntfs --force /tmp/ntfs.fs
sudo mount -t ntfs -o loop,uid=1000,gid=1000 /tmp/ntfs.fs /mnt
mkdir /tmp/from
touch /tmp/from/'a '
touch /tmp/from/' b '
mkdir /tmp/from/'c ' /tmp/from/' d '
rdiff-backup /tmp/from /mnt/bak
```

There is no error, and the output looks good to me:

```
$ ll /mnt/bak
total 0
-rwxrwxrwx. 1 ericl ericl   0 May 15 06:59 'a '
-rwxrwxrwx. 1 ericl ericl   0 May 15 07:00 ' b '
drwxrwxrwx. 1 ericl ericl   0 May 15 07:15 'c '
drwxrwxrwx. 1 ericl ericl   0 May 15 07:15 ' d '
drwxrwxrwx. 1 ericl ericl 248 May 15 07:15  rdiff-backup-data
```

So, there is a difference in file system... How did you create your NTFS file system?

**Comment by ericzolf** [comment] 2021-05-15 05:20
BTW, I tried with version 2.0.5 and with version 2.1.0a2.dev14+g6a9b88d, and the result is the same, so that the exact version shouldn't be the issue...

**Comment by brainchild0** [comment] 2021-05-15 13:09
I have ready access to three NTFS file systems at the moment, one  on my internal drive, one on a removable USB magnetic disk, and one on a memory card. For the partition on the internal drive, my results are as yours.

For the other two, I get this:

```
$ touch 'a'
$ touch ' a'
$ touch 'a '
touch: setting times of 'a ': No such file or directory
$ touch ' a '
touch: setting times of ' a ': No such file or directory
$ ls
' a'
a
```

I know it seems odd, but perhaps if you have removable media available, you might try using it in an attempt to reproduce.

**Comment by ericzolf** [comment] 2021-05-15 14:54
I can try but could it be that the file systems have been created on Windows vs. on Linux?

**Comment by brainchild0** [comment] 2021-05-15 15:43
> I can try but could it be that the file systems have been created on Windows vs. on Linux?

It's a fine idea, but based on current observations, another explanation is needed.

**Comment by ericzolf** [comment] 2021-05-16 11:33
Could you call `sudo file -s /dev/xxx` for each device?

**Comment by brainchild0** [comment] 2021-05-16 22:17
Internal Windows installation:



```
/dev/nvme0n1p4: DOS/MBR boot sector, code offset 0x52+2, OEM-ID "NTFS    ", sectors/cluster 8, Media descriptor 0xf8, sectors/track 63, heads 255, hidden sectors 1564672, dos < 4.0 BootSector (0x80), FAT (1Y bit by descriptor); NTFS, sectors/track 63, sectors 204799992, $MFT start cluster 786432, $MFTMirror start cluster 2, bytes/RecordSegment 2^(-1*246), clusters/index block 1, serial number 06b42697b42688ef; contains bootstrap BOOTMGR
```


Memory card:

```
/dev/sda1: DOS/MBR boot sector, code offset 0x52+2, OEM-ID "NTFS    ", sectors/cluster 8, Media descriptor 0xf8, sectors/track 63, heads 255, hidden sectors 65536, dos < 4.0 BootSector (0x80), FAT (1Y bit by descriptor); NTFS, sectors/track 63, sectors 499679231, $MFT start cluster 4, $MFTMirror start cluster 31229951, bytes/RecordSegment 2^(-1*246), clusters/index block 1, serial number 078ded05c028f54b9
```




USB magnetic disk:

```
/dev/sdb1: DOS/MBR boot sector, code offset 0x52+2, OEM-ID "NTFS    ", sectors/cluster 8, Media descriptor 0xf8, sectors/track 63, heads 255, hidden sectors 2048, dos < 4.0 BootSector (0x80), FAT (1Y bit by descriptor); NTFS, sectors/track 63, sectors 9767471103, $MFT start cluster 786432, $MFTMirror start cluster 2, bytes/RecordSegment 2^(-1*246), clusters/index block 1, serial number 07c30507e30504176; contains bootstrap BOOTMGR
```

**Comment by ericzolf** [comment] 2021-05-17 05:56
OK, the difference isn't how you format it or the type of drive, it's how you mount it:

* mounted as normal user e.g. through the UI or using `udisksctl mount --block-device /dev/sda1`, it fails like you describe:

```
/dev/sda1 on /run/media/ericl/5291712E0E79C514 type fuseblk (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096,uhelper=udisks2)
```

* whereas mounted normally as root, e.g. with `sudo mount -t ntfs -o uid=1000,gid=1000 /dev/sda1 /mnt` it succeeds, and adding the `nosuid,nodev` options doesn't change anything, so it's something more subtle:

```
/dev/sda1 on /mnt type fuseblk (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096)
```

OK, at least, I know how to reproduce.

**Comment by ericzolf** [comment] 2021-05-27 04:19
OK, the short version of the ticket tuxera/ntfs-3g#1 is that root doesn't use by default the option `windows_names` where it is used by udisks2 (as a side note, you probably want to use the option if you plan to re-use the same filesystem under Windows).

Anyway, it doesn't solve the fact that rdiff-backup doesn't detect properly the limitation, where it should, so still a bug...

**Comment by brainchild0** [comment] 2021-05-27 05:08
I suppose it is preferred that the integrity of the backup is preserved even when the volume remounted with different options, for incremental backup or restore.

**Comment by ericzolf** [comment] 2021-05-27 06:28
This isn't going to happen, it's your responsibility to make sure that the file system you use for your backup is robust (and doesn't change).

Doing otherwise would break two important principles of rdiff-backup:

1. we don't care about file systems types/names, we just test them for features and act accordingly. We care as little about ExFAT as about NTFS, they're just file systems with different features. If we would care about _potential_ features (or lack thereof), we would need to care about the type of each file system, and explicitly support a subset of them. We won't do this.
2. we backup files as much as possible similar to their source, so that a simple copy is mostly a "good enough" restore procedure. Being super-protective and quoting everything according to the worst possible file system would go against this principle. It ain't going to happen!

BTW, supporting changes of mount parameters would be the same as moving the backup repository from one file system to the next, which we have already clarified, we aren't going to support.

This said, it is true that the lack of feature wasn't properly detected by rdiff-backup, it is now fixed, pending merge.

**Comment by brainchild0** [comment] 2021-05-27 06:39
> BTW, supporting changes of mount parameters would be the same as moving the backup repository from one file system to the next, which we have already clarified, we aren't going to support.


From a development standpoint, this idea is an elegant one, but I'm concerned about the effect on users, most having no way to anticipate the  difference.

**Closed** 2021-05-28 18:29 UTC
Labels: bug, fixed
