### ISSUE TITLE
[ENH] Option to limit total size using remove increments

### ISSUE THREAD

**Issue by evoth** [rdiff-backup/rdiff-backup#911] opened 2023-08-12 09:34 UTC
## Is your feature request related to a problem? Please describe.

When making incremental backups, my main concern is the total size of the backup, since I want to keep as many increments as can fit on my drive. However, the `remove increments --older-than` option only accepts a time or number of increments before which to delete them.

## Describe the solution you'd like

An option to remove enough old increments so that the total size (of mirror + increments ideally) is below a given number of bytes. This could be implemented as another time format, but that may be awkward.

## Describe alternatives you've considered

I've considered using the output from `list increments --size` to achieve this functionality myself, but unfortunately it's prohibitively slow. It seems to recalculate the size every time, even if no files have changed. Maybe the sizes of the increments could be stored (if they're not already), and there could be a cache for the size of the mirror that's updated whenever a backup is performed.

Sorry if this is out of scope; I'll probably still try to implement this myself somehow since it would be really useful.

**Comment by ericzolf** [comment] 2023-08-13 10:06
Sounds like a duplicate of #281, which isn't going to be implemented any time soon (the time constraints of 'list increments --size` are also internal).
Anyway, what you can do is to remove always the oldest increment until you reach the required free size. If you do this regularly, e.g. after/before each backup, it shouldn't take a lot more time than if the feature would be implemented.

**Closed by ericzolf** 2023-08-13 10:06 UTC
Labels: enhancement, triage
