### ISSUE TITLE
[BUG] crash when paths with accents in a file --exclude-globbing-filelist

### ISSUE THREAD

**Issue by nuclimedia** [rdiff-backup/rdiff-backup#662] opened 2022-01-11 01:02 UTC
## Bug summary

rdiff-backup crash at biginning if you have paths with accents in a file --exclude-globbing-filelist

## Version, Python, Operating System

Using rdiff-backup version 2.0.0 with cpython /usr/bin/python3 version 3.8.10 on Linux-5.11.0-44-generic-x86_64-with-glibc2.29, fs encoding utf-8

## rdiff-backup call

`rdiff-backup --exclude-globbing-filelist=excludes.lst src_folder dest_folder`

excludes.lstz
```
[...]
/media/Nextcloud/data/admin/files/Vídeos/*
/media/Nextcloud/data/admin/files/Música/*
[...]
```

## What happened and what did you expect?

rdiff-backup crash and won't continue. Below I put the catch of the exception.

```
Exception 'string index out of range' raised of class '<class 'IndexError'>':
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 412, in Main
    take_action(rps)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 348, in take_action
    Backup(rps[0], rps[1])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 429, in Backup
    backup_set_select(rpin)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 456, in backup_set_select
    rpin.conn.backup.SourceStruct.set_source_select(rpin, select_opts,
  File "/usr/lib/python3/dist-packages/rdiff_backup/connection.py", line 526, in __call__
    return self.connection.reval(*(self.name, ) + args)
  File "/usr/lib/python3/dist-packages/rdiff_backup/connection.py", line 439, in reval
    raise result

Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 412, in Main
    take_action(rps)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 348, in take_action
    Backup(rps[0], rps[1])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 429, in Backup
    backup_set_select(rpin)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 456, in backup_set_select
    rpin.conn.backup.SourceStruct.set_source_select(rpin, select_opts,
  File "/usr/lib/python3/dist-packages/rdiff_backup/connection.py", line 526, in __call__
    return self.connection.reval(*(self.name, ) + args)
  File "/usr/lib/python3/dist-packages/rdiff_backup/connection.py", line 439, in reval
    raise result
IndexError: string index out of range
Fatal Error: Lost connection to the remote system
```

The problem is with the accents of the file excludes.lst. If i delete this two lines or change the accented characters with normal characters, it works without problems.

**Comment by ericzolf** [comment] 2022-01-11 07:47
Could you please try again with rdiff-backup v2.0.5? Many bugs have been fixed in-between, also regarding selection.

**Comment by ericzolf** [comment] 2022-01-11 07:50
In the meantime you should be able to replace the accented characters with a question mark or an asterisk (*).

**Comment by nuclimedia** [comment] 2022-01-19 23:53
> In the meantime you should be able to replace the accented characters with a question mark or an asterisk (*).

Yes, it's how i have it. It works, but it's not the best elegant solution i guess.

**Comment by ericzolf** [comment] 2022-01-20 12:12
Not the best elegant solution is probably to upgrade rdiff-backup :smile:

**Comment by ericzolf** [comment] 2022-04-23 15:33
I tried this and can't reproduce the issue with rdiff-backup 2.0.5 and 2.1 (from Git), hence closing.

**Closed by ericzolf** 2022-04-23 15:33 UTC
Labels: need review, need more info
