### ISSUE TITLE
Cannot build against current librsync version, 2.0.2

### ISSUE THREAD

**Issue by mhsmith** [rdiff-backup/rdiff-backup#36] opened 2018-09-08 09:53 UTC
Building rdiff-backup 1.2.8:

```
    _librsyncmodule.c: In function '_librsync_new_sigmaker':
    _librsyncmodule.c:63:17: error: 'RS_DEFAULT_STRONG_LEN' undeclared (first use in this function)
             (size_t)RS_DEFAULT_STRONG_LEN);
                     ^~~~~~~~~~~~~~~~~~~~~
    _librsyncmodule.c:63:17: note: each undeclared identifier is reported only once for each function it appears in
    _librsyncmodule.c:62:17: error: too few arguments to function 'rs_sig_begin'
       sm->sig_job = rs_sig_begin((size_t)blocklen,
                     ^~~~~~~~~~~~
    In file included from _librsyncmodule.c:25:0:
    C:/msys64/mingw64/include/librsync.h:397:11: note: declared here
     rs_job_t *rs_sig_begin(size_t new_block_len, size_t strong_sum_len,
               ^~~~~~~~~~~~
```

[This page](https://www.linuxglobal.com/librsync-error-rs_default_strong_len-undeclared/) suggests the following patch (I haven't tested it myself):
```
--- _librsyncmodule.c.ORIG 2006-11-11 23:32:01.000000000 -0800
+++ _librsyncmodule.c 2018-02-20 11:22:06.529111816 -0800
@@ -59,8 +59,8 @@
 if (sm == NULL) return NULL;
 sm->x_attr = NULL;

- sm->sig_job = rs_sig_begin((size_t)blocklen,
- (size_t)RS_DEFAULT_STRONG_LEN);
+ sm->sig_job = rs_sig_begin((size_t)blocklen, 8,
+ (size_t)RS_MD4_SIG_MAGIC);
 return (PyObject*)sm;
 }
```

**Comment by tom-ch1** [comment] 2019-01-20 23:04
I can confirm that this patch works

**Comment by mhsmith** [comment] 2019-04-09 16:18
I haven't pursued this problem and I never tested the patch: I only linked to it in case it was useful to others.

**Comment by ottok** [comment] 2019-08-02 19:14
Fixed for Debian in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=928885#28

**Comment by ericzolf** [comment] 2019-08-02 20:31
I'm a bit confused because the link to Debian only shows a change of librsync-dev version but nothing more. Furthermore the current code in the repository has already (more or less) the patch suggested initially, already required for version 1.0 of librsync. And the patch still involves MD4 as default hash (RS_MD4_SIG_MAGIC vs. RS_BLAKE2_SIG_MAGIC).

I have the impression that this issue could be closed (but I don't have a librsync2 library to check).

**Comment by ottok** [comment] 2019-08-09 07:27
Here you can find an overview of rsync-backup in Debian: https://tracker.debian.org/pkg/rdiff-backup

Here are the packaging sources: https://salsa.debian.org/python-team/applications/rdiff-backup

Here are the fixes:
- https://salsa.debian.org/python-team/applications/rdiff-backup/commit/2c06400c1dc4512506dc9854caa6374f71e88ef3
- https://salsa.debian.org/python-team/applications/rdiff-backup/commit/29b7b904891c03fa14baa9c83cf9a3fb4dd7f405

I will upstream all of these once the Python 3 branch is merged and master is good to go for further developments.

**Comment by ericzolf** [comment] 2019-08-11 06:41
I'm pretty sure this is fixed in my branch and can be closed. For reference, I have created #47 for the introduction of Blake2 as a possible more secure algorithm than MD4.

**Comment by ottok** [comment] 2019-08-12 15:07
I can also confirm that building agains librsync2 works with latest master.

Note that I also filed https://github.com/rdiff-backup/rdiff-backup/pull/56

**Comment by ericzolf** [comment] 2019-10-26 06:08
Also confirmed as I built on Windows, so we can close this issue.

**Closed by ericzolf** 2019-10-26 06:08 UTC
Labels: bug, need review
