### ISSUE TITLE
[BUG] `remove increments --older-than` returns an error when there is no increment to remove in v2.1.0a1

### ISSUE THREAD

**Issue by desseim** [rdiff-backup/rdiff-backup#616] opened 2021-08-15 21:25 UTC
## Bug summary

Using v2.1.0a1, calling *with the new or old interface*, removing increments with the `--older-than` option returns 1 (error) if there is no increment old enough to be removed.

## Version, Python, Operating System

```yaml
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - c:\Program Files\rdiff-backup\rdiff-backup.exe
  - info
  version: 2.1.0a1
python:
  executable: c:\Program Files\rdiff-backup\rdiff-backup.exe
  name: cpython
  version: 3.9.1
system:
  fs_encoding: utf-8
  platform: Windows-10-10.0.19041-SP0
...
```

## rdiff-backup call

```
"C:\Program Files\rdiff-backup-v210a1\rdiff-backup.exe" remove increments --older-than 3Y D:\  # returns 1
"C:\Program Files\rdiff-backup-v205\rdiff-backup.exe" --remove-older-than 3Y D:\  # returns 0
```

## What happened and what did you expect?

`rdiff-backup` v2.1.0a1 returns `1` while v2.0.5 returns `0`.

As a user, I would expect the command to return `0` (success) if it can access the backup directory and list its increments, meaning it runs without unexpected error, even if there is no matching increment to remove and it terminates without removing any.
This expectation seems consistent with how the `man` entry describes `rdiff-backup` return value:
````
If rdiff-backup finishes successfully, the exit status will be  0.   If
       there  is  an unrecoverable (critical) error, it will be non-zero (usu-
       ally 1, but don't depend on this  specific  value).   When  setting  up
       rdiff-backup  to  run  automatically (as from cron(8) or similar) it is
       probably a good idea to check the exit code.
````

Note that this "no matching increment found" case is different from the "specified increment not found" case of removing a given specific increment, where it does make sense to consider it an error if the increment doesn't exist.

## More information

My use case is running `rdiff-backup` in automated scripts and performing cleanup of old backups automatically.
The current behavior makes it impossible to check the exit code for potential execution error (e.g. "backup repository unaccessible") as suggested by the manual in such a use case.

**Comment by ericzolf** [comment] 2021-08-16 04:05
Well, this is disputable: you could have a typo in your script and never know that nothing is being done because the return code is 0. This said,  I'll stick to the behaviour of 2.0.5 by default. Thanks for reporting the issue.

**Comment by desseim** [comment] 2021-08-17 22:46
To address all possibilities we would need 3 return values, like `grep` does:
- increments found and deleted without errors
- no increment found and no error
- unexpected error occurred.

As long as we have only two, they can only determinate whether increments were found and deleted successfully or not, or whether an error occurred or not.

To clarify why I argued for the second of these choices (especially wrt the goal for the exit status stated in the manual):
the issue of a typo for example is usually determined interactively or at the script-testing phase, during which the user can review the output and notice an unexpected "No increment removed" output. On the other hand, automatic / scheduled scripts run unattended and in this case it is more useful to know when an unexpected error, which should be manually checked and addressed, happened.
Otherwise, scripts have to either ignore the result, or add convoluted pre-checks to only run a remove command when matching increments are present.
I'm sure there are use cases for automatically determining whether any increment has been removed or not, but I would assume they are more limited and less common.

In any way, thanks for addressing the change of behavior.

**Comment by ikus060** [comment] 2021-11-08 21:35
I would personally close this ticket as "Won't do". Current behaviour is satisfiable. Return an error if nothing was done. Simiar to `rm invalid`.

The only useful case as stated is within a script and I would leave the script writer the responsibility to handle that scenario the way they want by ignoring the exitcode or parsing the stdout.

**Comment by ericzolf** [comment] 2021-11-10 05:40
I could agree but for two reasons, I won't :grin: 

1. the behaviour isn't wanted, it came by chance, which probably means that something is wrong in the code, this should be addressed.
2. if rdiff-backup acted differently, we should stay consistent

**Closed** 2021-11-13 13:52 UTC

**Comment by desseim** [comment] 2022-11-02 03:29
I'd like to bring some attention back to this issue, as after being reverted to the original behavior in `v2.1.1a0`, it changed again from `v2.1.2b2` on:

```console
> & 'C:\Program Files\rdiff-backup-2.1.0a1\rdiff-backup.exe' --remove-older-than 3Y 'D:/'
WARNING: this command line interface is deprecated and will disappear, start using the new one as described with '--new --help'.
No increments older than Sun Nov  3 03:02:27 2019 found, exiting.
Action remove failed on run.
> echo $LASTEXITCODE
1  # "broken", as originally reported in this issue

> & 'C:\Program Files\rdiff-backup-2.1.1a0\rdiff-backup.exe' --remove-older-than 3Y 'D:/'
WARNING: this command line interface is deprecated and will disappear, start using the new one as described with '--new --help'.
NOTE: No increments older than Sun Nov  3 03:01:23 2019 found, exiting.
> echo $LASTEXITCODE
0  # "fixed" as per this issue, i.e. reverted to the behavior of `v2.0.x`

> & 'C:\Program Files\rdiff-backup-2.1.2b2-64\rdiff-backup.exe' --remove-older-than 3Y 'D:/'
WARNING: this command line interface is deprecated and will disappear, start using the new one as described with '--new --help'.
NOTE: No increments older than Sun Nov  3 03:01:05 2019 found, exiting.
WARNING: No increment is older than '3Y'
WARNING: Action remove emitted warnings, see previous messages for details
> echo $LASTEXITCODE
2  # new, different behavior

> & 'C:\Program Files\rdiff-backup-2.1.3b3-64\rdiff-backup.exe' remove increments --older-than 3Y 'D:/'
NOTE: No increments older than Sun Nov  3 03:00:00 2019 found, exiting.
WARNING: No increment is older than '3Y'
WARNING: Action remove emitted warnings, see previous messages for details
> echo $LASTEXITCODE
2
```

I guess this must be due to the following change having been affected to the `remove` command (`WARNING`s in the output of the `backup` command don't seem to affect its result value, I guess this will be for a future release):

> CHG: start to introduce more specific return codes (1 for error, 2 for warning, 4 for single file error, etc), which can be combined (e.g. 3 for error and warning), this will take time to introduce everywhere

So, this may be intentional and the change in behavior accepted, but given that it happened between 2 beta versions and given @ericzolf 's [last comment](<https://github.com/rdiff-backup/rdiff-backup/issues/616#issuecomment-964805434>) (especially point `2.`), I thought it might be accidental and should be reported.

**Comment by ericzolf** [comment] 2022-11-02 06:33
No, this time it is expected behavior indeed, as also documented in the man pages, but thanks for paying attention.

**Comment by ericzolf** [comment] 2022-11-02 06:40
I confirm that it's fixed, thanks to Frank:

```
$ sudo dnf install python3.11-devel python3.11
$ python3.11 -m venv /tmp/py311
$ source /tmp/py311/bin/activate
$ pip install rdiff-backup
Collecting rdiff-backup
  Using cached rdiff-backup-2.0.5.tar.gz (456 kB)
<FAILS!!!>
$ pip install rdiff-backup==2.1.3b3
[...]
Installing collected packages: PyYAML, rdiff-backup
    Running setup.py install for rdiff-backup ... done
Successfully installed PyYAML-6.0 rdiff-backup-2.1.3b3
$ rdiff-backup info [... etc ...]
```

Hence closing.

**Comment by desseim** [comment] 2022-11-02 09:11
> No, this time it is expected behavior indeed, as also documented in the man pages, but thanks for paying attention.

Alright, not that it is a problem, just not what I expected given the above (prior) discussion.

Is my understanding correct then, that, at some point, the `backup` command will also start to return `2` when it issued `WARNING`s?

Lastly, is [your last comment](<https://github.com/rdiff-backup/rdiff-backup/issues/616#issuecomment-1299652166>) perhaps intended for a different issue?
If not, could you please give a hint as to how it relates to this issue?

Thanks.

**Comment by ericzolf** [comment] 2022-11-02 12:22
Uups, last comment was indeed meant for another issue #773

**Comment by ericzolf** [comment] 2022-11-02 18:09
And, yes, the behaviour is expected to expand, as I find time.

**Comment by counterpoint** [comment] 2024-03-03 17:24
Sorry, but this is a real nuisance. It's usual to be running rdiff-backup in scripts triggered by cron. The way mine are set up, I get an email if there is an error, but nothing if not. I am now suffering daily emails just to tell me that there didn't happen to be anything to remove, even though everything is working perfectly. Yes, I could elaborate the scripts to ignore warnings - but then I might miss something important (unlike the fact that there isn't always an old item to remove). If we must have a non zero return code for this situation, please can it be different from other warnings?

**Comment by hujuice** [comment] 2025-01-19 15:28
Well, I also agree that `remove increments --older-than` should not rise a warning if there are no increments.
Like many, I am "flooded" by daily emails (that I ignore, at this point), because of warnings that warn me that there were no increments.

Now I prepended this to one of my scripts, to be sure to have daily changes.
`/bin/date > "${BASE_PATH}/avoid-rdiff-backup-warnings-if-no-increments"`
