### ISSUE TITLE
[BUG] File used by another process.

### ISSUE THREAD

**Issue by user655362020** [rdiff-backup/rdiff-backup#392] opened 2020-06-05 06:33 UTC
## Bug summary

Getting file used by another process error. This is the first backup.

## Version, Python, Operating System
Windows 10 Bugfix release 2.0.3
```
2020-06-05 11:41:40.304281 +0530  <CLIENT-8640>  Exception '(32, 'GetFileAttributes', 'The process cannot access the file because it is being used by another process.')' raised of class '<class 'pywintypes.error'>':
  File "rdiff_backup\robust.py", line 35, in check_common_error
  File "rdiff_backup\rpath.py", line 1412, in append
  File "rdiff_backup\rpath.py", line 1082, in __init__
  File "rdiff_backup\rpath.py", line 1108, in setdata
  File "rdiff_backup\rpath.py", line 425, in make_file_dict

2020-06-05 11:41:40.304281 +0530  <CLIENT-8640>  Exception '(32, 'GetFileAttributes', 'The process cannot access the file because it is being used by another process.')' raised of class '<class 'pywintypes.error'>':
  File "rdiff_backup\Main.py", line 393, in error_check_Main
  File "rdiff_backup\Main.py", line 415, in Main
  File "rdiff_backup\Main.py", line 351, in take_action
  File "rdiff_backup\Main.py", line 440, in Backup
  File "rdiff_backup\backup.py", line 39, in Mirror
  File "rdiff_backup\backup.py", line 267, in patch
  File "rdiff_backup\rorpiter.py", line 202, in FillInIter
  File "rdiff_backup\backup.py", line 114, in get_diffs
  File "rdiff_backup\backup.py", line 196, in get_sigs
  File "rdiff_backup\backup.py", line 361, in __next__
  File "rdiff_backup\rorpiter.py", line 109, in Collate2Iters
  File "rdiff_backup\rorpiter.py", line 376, in __next__
  File "rdiff_backup\selection.py", line 138, in Iterate_fast
  File "rdiff_backup\selection.py", line 122, in diryield
  File "rdiff_backup\robust.py", line 35, in check_common_error
  File "rdiff_backup\rpath.py", line 1412, in append
  File "rdiff_backup\rpath.py", line 1082, in __init__
  File "rdiff_backup\rpath.py", line 1108, in setdata
  File "rdiff_backup\rpath.py", line 425, in make_file_dict

Traceback (most recent call last):
  File "rdiff_backup\rorpiter.py", line 105, in Collate2Iters
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rdiff-backup", line 32, in <module>
  File "rdiff_backup\Main.py", line 393, in error_check_Main
  File "rdiff_backup\Main.py", line 415, in Main
  File "rdiff_backup\Main.py", line 351, in take_action
  File "rdiff_backup\Main.py", line 440, in Backup
  File "rdiff_backup\backup.py", line 39, in Mirror
  File "rdiff_backup\backup.py", line 267, in patch
  File "rdiff_backup\rorpiter.py", line 202, in FillInIter
  File "rdiff_backup\backup.py", line 114, in get_diffs
  File "rdiff_backup\backup.py", line 196, in get_sigs
  File "rdiff_backup\backup.py", line 361, in __next__
  File "rdiff_backup\rorpiter.py", line 109, in Collate2Iters
  File "rdiff_backup\rorpiter.py", line 376, in __next__
  File "rdiff_backup\selection.py", line 138, in Iterate_fast
  File "rdiff_backup\selection.py", line 122, in diryield
  File "rdiff_backup\robust.py", line 35, in check_common_error
  File "rdiff_backup\rpath.py", line 1412, in append
  File "rdiff_backup\rpath.py", line 1082, in __init__
  File "rdiff_backup\rpath.py", line 1108, in setdata
  File "rdiff_backup\rpath.py", line 425, in make_file_dict
pywintypes.error: (32, 'GetFileAttributes', 'The process cannot access the file because it is being used by another process.')
[8640] Failed to execute script rdiff-backup
```

## rdiff-backup call

How did you call rdiff-backup, with which parameter:

```
rdiff-backup -v9 --exclude-if-present ".nobackup" --exclude-if-present ".archive" --exclude "**/Downloads" --exclude "**/downloads" --exclude "**/System Volume Information" --exclude "**/$RECYCLE.BIN" --exclude-other-filesystems --no-compression-regexp --verify "D:/" "H:/rdiff/D-Data"
```

## What happened and what did you expect?
Getting file used by another process. I can verify that the file (after which this exception occurs) is not used by other process because I can move it. The file is the last file that is supposed to be backed up (Backup should end after that file). Checksum of backed up file and the original file matches.

**Comment by ericzolf** [comment] 2020-06-05 08:06
Is this something you can repeat with `-v9` or did it only happen once? And with which file exactly? Without more information, I can't reproduce your issue, which I've never encountered.

**Comment by user655362020** [comment] 2020-06-06 06:49
Windows paging is causing the error. I disabled paging for the partition and backup completed successfully. I re-enabled it for the drive and backup failed with above error. I tried to exclude the pagefile.sys with ```--exclude **.sys```, ```--exclude **pagefile.sys```, ```--exclude **/pagefile.sys``` 
but it did not work.

I am doing a ```cd D:``` before running rdiff-backup.

**Comment by ericzolf** [comment] 2020-06-06 07:46
OK, I can reproduce the error with `rdiff-backup -v9 --exclude C:/ProgramData --exclude "C:/Program Files" --exclude "C:/Program Files (x86)" --exclude C:/Python37 --exclude C:/Windows --exclude C:/Users/vagrant --exclude C:/pagefile.sys C:/ myuser@mylinux::/tmp/bakwin1` (and a few more issues on top...).

How did you come to the conclusion that pagefile.sys was the issue? I don't see any hint in the debug messages.

**Comment by user655362020** [comment] 2020-06-06 08:10
My windows installation is in C: Drive. My data is in D: Drive. I had changed windows paging settings to use D: drive for pagefile instead of C:

Right now, I can move every file and folder in the D: drive except pagefile.sys (Used by windows).

Further when I disable paging on D: drive, the pagefile.sys is removed from D: drive and rdiff-backup completes successfully.

**Comment by ericzolf** [comment] 2020-06-06 08:42
I understood this, my question was more how you came to the idea that paging might be the issue. Was it just a pure guess or did you see something, e.g. an error message, which made you think that it might be the root cause?

**Comment by user655362020** [comment] 2020-06-06 08:46
No. It was just a pure guess. I was sure no file was being accessed other than pagefile.

Also a way to backup a windows partition would be to first create a snapshot using volume shadow service to prevent the "File in use" errors

**Comment by ericzolf** [comment] 2020-06-06 08:54
Anyway, here my thoughts of what needs to be fixed so far:

1. the exception `Exception '(32, 'GetFileAttributes', 'The process cannot access the file because it is being used by another process.')' raised of class '<class 'pywintypes.error'>'` must be added to the ignored errors in robust.py
2. at the same time, the exception should be packed into a more generic exception so that it is known to any platform even when transferring the exception to a linux client/server (which doesn't know about `pywintypes.error`). Currently the Linux side in my tests says while "unpickling" `Sending back exception No module named 'pywintypes' of type <class 'ModuleNotFoundError'>` and fails completely at: `File "/usr/lib64/python3.8/site-packages/rdiff_backup/connection.py", line 295, in _get
    result = pickle.loads(data)`
3. the exception shouldn't be raised without a clear notice which file is impacted, probably an additional debug message in rpath.py when initiating the file.
4. actually the file should be excluded _before_ it is being accessed in any way or form.

That's quite a lot and I might not be able to fix all these in one PR, I might create separate issues for some aspects.

**Comment by ericzolf** [comment] 2020-06-06 09:39
Note for myself: resolution for point 4 of the above list is also the root cause for #245 so both should be fixed together.

**Comment by user655362020** [comment] 2020-06-06 11:01
Would it be possible to write name and path of files not backed up in a separate log file (and remove it when backup itself is removed) ?

Also display the files not backed up on terminal ?

**Comment by ericzolf** [comment] 2020-06-06 11:23
> Would it be possible to write name and path of files not backed up in a separate log file (and remove it when backup itself is removed) ?

That would be a separate enhancement request, if you don't mind.
 
> Also display the files not backed up on terminal ?

This is normally done as long as you have the right (terminal) verbosity.

**Comment by user655362020** [comment] 2020-06-06 11:26
All right. Thanks for looking into this issue.

**Closed** 2020-06-15 06:02 UTC
Labels: bug
