### ISSUE TITLE
[ENH] Delete / Thin out backups

### ISSUE THREAD

**Issue by user-na** [rdiff-backup/rdiff-backup#560] opened 2021-04-11 19:38 UTC
## Is your feature request related to a problem? Please describe.

When reaching disk-space limits, deleting some backup history is a must. Currently the only way to do this is deleting bakups older than a threshold. But I actually don't want to loose all information before that time threshold.
Another closely related issue is that some changes which are done by mistake (create/delete large files) cannot be un-done before they reach their end-of backup date.

## Describe the solution you'd like

It would be great do delete backups in the middle of the chain, rather than only at the end. Fore the last recent backup there is a tool which actually tricks rdiff-backup into doing this [rdiff-backup-regress](https://www.timedicer.co.uk/programs/help/rdiff-backup-regress.sh.php). But it would be very beneficial to do this to a much wider extend. The idea would be to merge 2 deltas dn and dn+1 (oldest , .. ,dn, dn+1, ..., current). After the merging it should look like if all dn did not exist and that dn+1 is the delta for dn-1. With this functionality many new possible features would open up. Calls like

... -older-than 30d - thin-out 7d

which delete (merge) all backups which are older than 30 days in a way to be min7 days appart would be a total game changer for my application of rdiff-backup

## Describe alternatives you've considered

One could have different backup folder with different backup frequencies. But that solution is very poor compared to the request.

**Comment by ericzolf** [comment] 2021-04-11 20:00
Isn't it a duplicate of #257 ?

**Comment by user-na** [comment] 2021-04-11 20:01
seems to be. Searched the issues before I wrote this, but obviously missed that. - Sorry

**Comment by ericzolf** [comment] 2022-11-05 16:12
The delete bad deltas can be done with rdiff-backup-delete, hence closing this issue as duplicate.

**Closed by ericzolf** 2022-11-05 16:12 UTC
Labels: enhancement
