### ISSUE TITLE
[ENH] need more Windows docs

### ISSUE THREAD

**Issue by GusevVictor** [rdiff-backup/rdiff-backup#516] opened 2021-01-13 21:25 UTC
## Is your feature request related to a problem? Please describe.

Dear all, I think there is no good documentation for Windows users.

## Describe the solution you'd like

I think we need to have an answer for the following questions:

1. Can rdiff-backup save Windows ACL?
2. How rdiff-backup save Windows ACL?
3. If I backup from Windows to Linux (zfs), do I need setup zfs for that? Like this one:

```
zfs set aclmode=passthrough storage0
zfs set aclinherit=passtrhough storage0
```

4. Do I need setup pylibacl pyxattr on linux side for make a correct backup Windows?
5. Is it possible to create a snapshot of Windows VOLUME before backup and delete after? - If it is possible need some examples.
6. Is it possible to run rdiff-backup 2.x on Windows 2003 if I have Microsoft Visual C++ 2008 redistributables installed on it?

## Describe alternatives you've considered

May be include this question (or part?) to FAQ?

## Additional context

Very nice to have any answer for my questions! Thank a lot!

**Comment by ikus060** [comment] 2021-01-13 22:16
>    Can rdiff-backup save Windows ACL?
Yes. The pre-compiled version provided for Windows include all the dependencies to save the ACL.

>    How rdiff-backup save Windows ACL?
I don't see alot of details in our documentation regarding xattr and ACL, those are safe in a rdiff-backup specific format under ./rdiff-backup-data/win_access_control_lists.*

>    If I backup from Windows to Linux (zfs), do I need setup zfs for that? Like this one:
Nothing special to be done for ZFS or any other FS supporting or not supporting ACL. This information is stored as files.

>    Do I need setup pylibacl pyxattr on linux side for make a correct backup Windows?
That i'm not sure. I had different experience in the pas with rdiff-backup v.1.2.8. I believe you need pylibacl and pyxattr on your linux server.

>    Is it possible to create a snapshot of Windows VOLUME before backup and delete after? - If it is possible need some examples.
It's possible, but rdiff-backup is not supporting this feature out of the box.

>    Is it possible to run rdiff-backup 2.x on Windows 2003 if I have Microsoft Visual C++ 2008 redistributables installed on it?
Don't know.

**Comment by ericzolf** [comment] 2021-01-17 18:39
@GusevVictor it's open source, feel free to test what isn't properly documented and offer your documentation.

**Comment by GusevVictor** [comment] 2021-01-18 06:58
> 
> 
> @GusevVictor it's open source, feel free to test what isn't properly documented and offer your documentation.

Yes. I test it right now. Thanks!

**Comment by ericzolf** [comment] 2021-01-29 18:39
But also document the results for the rest of us!

**Comment by GusevVictor** [comment] 2021-01-29 23:13
> 
> 
> But also document the results for the rest of us!

Hi! I have fail with it. :( There is some problem with use rdiff backup with Windows. 

There is big problem with snapshot. You need to stop any write to location of backup when you do backup or you need to create script for make snap and destroy it after backup.

You need to install ssh server for Windows and configure it.
You need to open ssh port and make real ip address if you want to backup notebook for example.

I have script for make a snapshot but rdiff-backup can't backup Folder with space in name junk link and so on.

The next big problem that rdiff-backup not good for Windows at all because it make reverse diff. 
For example, if you use a *.docx file when you save it, Word make a NEW docx file (zip archive in fact), because of this you need to waste CPU for reverse diff and diff will have the same size as old file.

Because of this there is not any reason to use rdiff-backup in general Windows env. I suppose rdiff-backup on Windows will be good in very specific case only.

Because of many problem with rdiff-backup for Windows I have switch from rdiff-backup to burp backup! - https://burp.grke.org/ 


rdiff-backup is very good in some scenaries, for example: I use it for backup zimbra 3TB (Linux), alfresco, gateway linux and so on. - That is good because it can be agent less (sshfs)! And if you have DB and you don't want to setup complex backup strategy you can do snap and backup it.

For Windows I think I will use burp backup (I test in for now). - In burp backup I can switch mode of backup - reverse diff or just hard link. I can backup external client, burp can do VSS snapshot and so on!

**Comment by ericzolf** [comment] 2021-01-30 04:36
OK, I created a new enhancement request #520 for the snapshot capability, but don't hold your breath, not a priority right now.
Else, you can explicitly exclude certain files from the compression using `--no-compression-regexp` but that's not exactly what you need; this said, the problem is not specific to Windows and there are enough file types which profit from reverse backup, IMHO the issue will be the same with any compression algorithm, but try your luck.

And I'm surprised when you say that rdiff-backup can't backup folders with space in them, but I might have misunderstood you.

Anyway, no software can cover all requirements, so Burp might be a valid alternative for you.

**Comment by ericzolf** [comment] 2021-02-13 18:25
Closing as I don't expect more to come out of this issue. Re-open if you still need help.

**Closed by ericzolf** 2021-02-13 18:25 UTC
