### ISSUE TITLE
Bugreport: "Warning: modification time of XYZ/rdiff-backup.tmp.231316 isbefore 1970

### ISSUE THREAD

**Issue by tverrbjelke** [rdiff-backup/rdiff-backup#6] opened 2016-03-09 21:10 UTC
Warning: modification time of /mnt/drive/backup-lasse/Archiv/lasse_home/andreas/Documents/CodeProjects/CCC2011/r0ket/Archiv/original-firmware/filesystem/rdiff-backup.tmp.231316 isbefore 1970
Exception '[Errno 5] Input/output error: '/mnt/drive/backup-lasse/Archiv/lasse_home/andreas/Documents/CodeProjects/Cpp/Experiments/branches/.svn/prop-base'' raised of class '<type 'exceptions.OSError'>':
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 304, in error_check_Main
    try: Main(arglist)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 324, in Main
    take_action(rps)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 280, in take_action
    elif action == "backup": Backup(rps[0], rps[1])
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 346, in Backup
    backup.Mirror(rpin, rpout)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 38, in Mirror
    DestS.patch(dest_rpath, source_diffiter)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 232, in patch
    ITR(diff.index, diff)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/rorpiter.py", line 284, in **call**
    branch.start_process(*args)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 626, in start_process
    if diff_rorp.isdir(): self.prepare_dir(diff_rorp, self.base_rp)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 654, in prepare_dir
    base_rp.mkdir()
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/rpath.py", line 983, in mkdir
    self.conn.os.mkdir(self.path)

Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 30, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 304, in error_check_Main
    try: Main(arglist)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 324, in Main
    take_action(rps)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 280, in take_action
    elif action == "backup": Backup(rps[0], rps[1])
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 346, in Backup
    backup.Mirror(rpin, rpout)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 38, in Mirror
    DestS.patch(dest_rpath, source_diffiter)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 232, in patch
    ITR(diff.index, diff)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/rorpiter.py", line 284, in **call**
    branch.start_process(*args)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 626, in start_process
    if diff_rorp.isdir(): self.prepare_dir(diff_rorp, self.base_rp)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 654, in prepare_dir
    base_rp.mkdir()
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/rpath.py", line 983, in mkdir
    self.conn.os.mkdir(self.path)
OSError: [Errno 5] Input/output error: '/mnt/drive/backup-lasse/Archiv/lasse_home/andreas/Documents/CodeProjects/Cpp/Experiments/branches/.svn/prop-base'

**Comment by afoster** [comment] 2016-03-09 23:45
Hi @tverrbjelke , can you please give us some more info on the device and filesystem mounted at `/mnt/drive`. And is it otherwise healthy?

**Comment by anomaly256** [comment] 2018-01-12 04:07
Hi @tverrbjelke, this does look like an issue with the underlying file system more than with rdiff-backup itself (OSError on directory creation).  Were you able to find the cause of this issue?  If you still believe it's an issue with rdiff-backup we will need to try to recreate it, or examine the backup files if you still have them.  I'll keep this issue open for a while.  If we don't hear back from you in a couple weeks we'll close it.

**Comment by ericzolf** [comment] 2019-08-11 07:07
After more than one year, we can call it a day. Closing.

**Closed by ericzolf** 2019-08-11 07:07 UTC
Labels: support
