### ISSUE TITLE
Testing Codacy

### ISSUE THREAD

**Issue by ottok** [rdiff-backup/rdiff-backup#420] opened 2020-07-06 17:38 UTC
I am testing https://app.codacy.com/gh/rdiff-backup/rdiff-backup/dashboard and will use this issue for notes about what I've learned.

Let me know if you want an invitation to the Codacy org.

**Comment by ericzolf** [comment] 2020-07-06 17:47
The problem is that it applies to all PRs, can you change this, make it only optional? It doesn't help me right now...

**Comment by ottok** [comment] 2020-07-06 17:53
Fixed it now, but seems existings PRs need to be updated before the status changes.. :(

**Comment by ericzolf** [comment] 2020-07-07 05:21
The 3 comments I had were rather useless, 2 were plain wrong. And now I need to wait for the pipeline to merge my PR.

Two questions:

* Which issue are you actually trying to tackle which we haven't yet tackled with flake8? I don't really care about markdown formatting.
* Our pipeline is taking long, so I don't think that we should introduce blocking checks that can't be done also locally, like flake8.

Honestly, my first impression is very negative and I'm currently not amused.

**Comment by ericzolf** [comment] 2020-07-07 05:30
And with each new commit, you get new comments from this tool if you've not fixed the perceived issues. My opinion is made, please shut it off. This is a major pain without added value.

**Comment by ericzolf** [comment] 2020-07-07 06:15
And the comments given by the tool spam me with e-mails on top of it.

**Comment by ottok** [comment] 2020-07-07 13:09
The tools finds quite a lot of issues, so having it as a CI test that fails on PRs is too hard. The optimal setting seems to be having this add comments to the PR based on issues it finds:
![image](https://user-images.githubusercontent.com/668724/86785722-b80b3f80-c06b-11ea-89de-8204d68746bd.png)


This is pretty smart, since each finding is it's own comment and attached to the line where the issue it. When fixed, each comment can be marked as "resolved".

The wording is however a bit vague and causes difficulties for developers to understand and address them. Based on the negative feedback, I disabled it now.

The page at https://app.codacy.com/gh/rdiff-backup/rdiff-backup/dashboard is however still visible.

**Comment by ericzolf** [comment] 2020-07-08 05:24
The comments were not even attached to the right line though. OK, closing the issue.

**Closed by ericzolf** 2020-07-08 05:24 UTC
Labels: enhancement
