### ISSUE TITLE
[BUG] WinError 206

### ISSUE THREAD

**Issue by maxpagani** [rdiff-backup/rdiff-backup#861] opened 2023-02-27 17:16 UTC
## Bug summary

rdiff-backup crashes reporting FileNotFoundError if the file name (path, file and extensions) is too long.

## Version, Python, Operating System

Call `rdiff-backup info` (version >= 2.1) or `rdiff-backup -v9` and replace the following line with the output, repeat for each environment impacted:

```yaml
rdiff-backup 2.2.4
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
rdiff-backup.exe -v5 --no-acls F:\home\ \\nas01\max-backup\F_home
```

## What happened and what did you expect?

I got the following error message and the backup stopped.

```text
Traceback (most recent call last):
  File "rdiffbackup\run.py", line 170, in <module>
  File "rdiffbackup\run.py", line 37, in main
  File "rdiffbackup\run.py", line 105, in main_run
  File "rdiffbackup\actions\backup.py", line 159, in run
  File "rdiff_backup\backup.py", line 39, in mirror_compat200
  File "rdiff_backup\backup.py", line 197, in patch
  File "rdiff_backup\rorpiter.py", line 146, in __call__
  File "rdiff_backup\backup.py", line 595, in fast_process_file
  File "rdiff_backup\longname.py", line 152, in get_mirror_inc_rps
  File "rdiff_backup\longname.py", line 135, in find_inc_pair
  File "rdiff_backup\longname.py", line 313, in _check_new_index
  File "rdiff_backup\longname.py", line 290, in wrap_call
  File "rdiff_backup\longname.py", line 306, in make_parent
  File "rdiff_backup\rpath.py", line 802, in makedirs
  File "os.py", line 225, in makedirs
FileNotFoundError: [WinError 206] Nome del file o estensione troppo lunga: b'//nas01/max-backup/F_home/rdiff-backup-data/increments/max/AppData/Local/Microsoft/VisualStudio/16.0_42bab3b0/VTC/06f6c133f782d434f6f40eec0a900ca3/~PC/PT/CSharp/iOS Extensions/ContentBlockerExtension.zip/Resources/Images.xcassets/AppIcons.appiconset'
[28836] Failed to execute script 'run' due to unhandled exception!
```

I expect rdiff-backup to be able to cope with long path files. I tried to create a file in the directory via file explorer and open it with the Notepad++ application without any problem. This suggests that there could be a Windows API that bypasses the filename length limit.

As a temporary workaround, rdiff-backup could catch the exception, log the problem and proceed with the running backup.

## More information

If you can, please repeat the action leading to the error, adding the option `-v9` and attach the output to this bug report.

```
D:\home\rdiff-backup>rdiff-backup.exe -v9 --no-acls F:\home\ \\nas01\max-backup\F_home
WARNING: this command line interface is deprecated and will disappear, start using the new one as described with '--new --help'.
2023-02-27 18:15:21.641869 +0100  <CLIENT-24528>  DEBUG: Runtime information =>{'exec': {'version': '2.2.4', 'api_version': {'default': 200, 'min': 200, 'max': 201, 'actual': 0}, 'argv': ['rdiff-backup.exe', '-v9', '--no-acls', 'F:\\home\\', '\\\\nas01\\max-backup\\F_home'], 'parsed': {'api_version': None, 'current_time': None, 'force': False, 'fsync': True, 'null_separator': False, 'new': False, 'chars_to_quote': None, 'parsable_output': False, 'remote_schema': None, 'remote_tempdir': None, 'ssh_compression': True, 'tempdir': None, 'terminal_verbosity': None, 'use_compatible_timestamps': False, 'verbosity': 9, 'restrict': None, 'restrict_read_only': None, 'restrict_update_only': None, 'ssh_no_compression': False, 'create_full_path': False, 'compression': True, 'not_compressed_regexp': '(?i).*\\.(7z|aac|arj|asc|avi|bik|bz|bz2|deb|docx|flac|flv|gif|gpg|gz|jp2|jpeg|jpg|jsonlz4|lharc|lz4|lzh|lzma|lzo|m4a|m4v|mdf|mkv|mov|mozlz4|mp3|mp4|mpeg|mpg|oga|ogg|ogm|ogv|opus|pgp|pk3|png|rar|rm|rpm|rz|shn|tgz|tzst|vob|webm|webp|wma|wmv|xlsx|xz|z|zip|zoo|zst)$', 'selections': None, 'acls': False, 'carbonfile': True, 'compare_inode': True, 'eas': True, 'hard_links': True, 'resource_forks': True, 'never_drop_acls': False, 'group_mapping_file': None, 'preserve_numerical_ids': False, 'user_mapping_file': None, 'file_statistics': True, 'print_statistics': False, 'allow_duplicate_timestamps': False, 'restrict_path': None, 'restrict_mode': 'read-write', 'action': 'backup', 'compare_at_time': None, 'compare_hash_at_time': None, 'compare_full_at_time': None, 'list_at_time': None, 'list_changed_since': None, 'remove_older_than': None, 'restore_as_of': None, 'verify_at_time': None, 'locations': ['F:\\home\\', '\\\\nas01\\max-backup\\F_home']}}, 'python': {'name': 'cpython', 'executable': 'D:\\home\\rdiff-backup\\rdiff-backup.exe', 'version': '3.10.7'}, 'system': {'platform': 'Windows-10-10.0.19044-SP0', 'fs_encoding': 'utf-8'}}<=
2023-02-27 18:15:21.653869 +0100  <CLIENT-24528>  * Using repository '//nas01/max-backup/F_home'
2023-02-27 18:15:21.656870 +0100  <CLIENT-24528>  NOTE: Found interrupted initial backup in data directory //nas01/max-backup/F_home/rdiff-backup-data. Removing...
2023-02-27 18:15:21.656870 +0100  <CLIENT-24528>  DEBUG: Deleting (recursively) path //nas01/max-backup/F_home/rdiff-backup-data
2023-02-27 18:15:21.656870 +0100  <CLIENT-24528>  DEBUG: Removing directory //nas01/max-backup/F_home/rdiff-backup-data
2023-02-27 18:15:22.878509 +0100  <CLIENT-24528>  * Cleaning up
Traceback (most recent call last):
  File "rdiff_backup\rpath.py", line 902, in delete
  File "rdiff_backup\rpath.py", line 808, in rmdir
OSError: [WinError 145] La directory non è vuota: b'//nas01/max-backup/F_home/rdiff-backup-data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rdiffbackup\run.py", line 170, in <module>
  File "rdiffbackup\run.py", line 37, in main
  File "rdiffbackup\run.py", line 99, in main_run
  File "rdiffbackup\actions\backup.py", line 102, in setup
  File "rdiffbackup\locations\repository.py", line 101, in setup
  File "rdiffbackup\locations\repository.py", line 683, in _create
  File "rdiffbackup\locations\repository.py", line 732, in _clean_failed_initial_backup
  File "rdiff_backup\rpath.py", line 906, in delete
  File "shutil.py", line 749, in rmtree
  File "shutil.py", line 614, in _rmtree_unsafe
  File "shutil.py", line 614, in _rmtree_unsafe
  File "shutil.py", line 614, in _rmtree_unsafe
  [Previous line repeated 12 more times]
  File "shutil.py", line 623, in _rmtree_unsafe
  File "shutil.py", line 621, in _rmtree_unsafe
OSError: [WinError 145] La directory non è vuota: b'//nas01/max-backup/F_home/rdiff-backup-data\\increments\\max\\AppData\\Local\\Microsoft\\VisualStudio\\16.0_42bab3b0\\VTC\\06f6c133f782d434f6f40eec0a900ca3\\~PC\\PT\\CSharp\\iOS Extensions\\ContentBlockerExtension.zip\\Resources'
[24528] Failed to execute script 'run' due to unhandled exception!

```

**Comment by ericzolf** [comment] 2023-02-28 05:38
This is a duplicate of #782 - the difficulty is that Windows declares a file with a too long filename to be not-found/non-existent, it's even the first time that I see this WinError 206 which seems more explicit. Possibly, it's due to the remote file system.

**Closed** 2023-02-28 05:47 UTC
Labels: duplicate

**Comment by ericzolf** [comment] 2023-02-28 07:18
Few questions to better understand the issue:

1. what does the `reg query ...` from https://github.com/rdiff-backup/rdiff-backup/blob/master/docs/Windows-README.adoc#installation give you back?
2. what happens if you enable long file names using `reg add ...` from above (if not yet done)?
3. as you wrote that you created a file with Notepad++ in the same directory, you really meant `//nas01/max-backup/F_home/rdiff-backup-data/increments/max/AppData/Local/Microsoft/VisualStudio/16.0_42bab3b0/VTC/06f6c133f782d434f6f40eec0a900ca3/~PC/PT/CSharp/iOS Extensions/ContentBlockerExtension.zip/Resources/Images.xcassets/`? What was the name of the file you created? How many characters? Can you increase it to 19 or 20 characters?
4. It would be interesting to know which kind of error you get if doing your backup to a local directory (with the same path length).

You should fully remove the backup repository between two tests to avoid side effects.

**Comment by maxpagani** [comment] 2023-03-02 13:22
The reg query reported my "long path support" was disabled. After enabling it, the backup went fine. Sorry for not having read the docs, my fault.
Still, it would be nice for rdiff-backup to handle this gracefully and, maybe point to the documentation or provide the command for a possible solution to the problem.
Thank you.

**Comment by ericzolf** [comment] 2023-03-02 17:42
No worry. I fully agree that it should be better handled, but Linux knows the ENAMETOOLONG error, easy to catch and handle, Windows has non specific and changing errors.
